ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Inc/bsp/bsp_led.h File Reference
bsp_led.h File Reference
Board Support Package - LED Driver.
#include <stdint.h>
Functions
void LED_On (void)
Turn LED on.
void LED_Off (void)
Turn LED off.
void LED_Toggle (void)
Toggle LED state.
void LED_Blink (uint32_t on_ticks, uint32_t off_ticks)
Blink LED with specified timing.
Detailed Description
Board Support Package - LED Driver.
Version
0.1.0
Simple LED control interface for the onboard LED.
Hardware:
LED connected to PE3 (active high)
Author
Souham Biswas
Date
2026
Copyright
Copyright (c) 2026 ICARUS Project
Definition in file bsp_led.h.
Function Documentation
LED_Blink()
void LED_Blink (uint32_t Hdelay, uint32_t Ldelay)
Blink LED with specified timing.
Parameters
[in] on_ticks Duration LED is on (in OS ticks)
[in] off_ticks Duration LED is off (in OS ticks)
Note
Uses task_active_sleep() - must be called from task context
Blink LED with specified timing.
Turns LED on for specified duration, then off for specified duration. Uses task_active_sleep() for non-blocking delays.
Parameters
[in] Hdelay LED on duration in OS ticks
[in] Ldelay LED off duration in OS ticks
Precondition
GPIO must be initialized (MX_GPIO_Init called)
Must be called from task context (uses task_active_sleep)
Note
Total blink period = Hdelay + Ldelay ticks
Definition at line 153 of file retarget_hal.c.
References E3_GPIO_Port, E3_Pin, and task_active_sleep().
Referenced by main(), and os_heartbeat_task().
LED_Off()
void LED_Off (void)
Turn LED off.
Sets PE3 GPIO pin low to turn off the onboard LED.
Precondition
GPIO must be initialized
Definition at line 178 of file retarget_hal.c.
References E3_GPIO_Port, and E3_Pin.
Referenced by os_heartbeat_task().
LED_On()
void LED_On (void)
Turn LED on.
Turn LED on.
Sets PE3 GPIO pin high to illuminate the onboard LED.
Precondition
GPIO must be initialized
Definition at line 167 of file retarget_hal.c.
References E3_GPIO_Port, and E3_Pin.
Referenced by os_heartbeat_task().
LED_Toggle()
void LED_Toggle (void)
Toggle LED state.