ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Inc/bsp/bsp_error.h File Reference
bsp_error.h File Reference
Board Support Package - Error Handling.
#include <stdint.h>
Enumerations
enum bsp_status_t {
BSP_OK = 0 , BSP_ERROR = 1 , BSP_ERROR_TIMEOUT = 2 , BSP_ERROR_BUSY = 3 ,
BSP_ERROR_PARAM = 4 , BSP_ERROR_MEMORY = 5 , BSP_ERROR_HARDWARE = 6
}
System error codes.
Functions
void Error_Handler (void)
System error handler.
void assert_failed (uint8_t *file, uint32_t line)
Assert handler with location info.
Detailed Description
Board Support Package - Error Handling.
Version
0.1.0
System error handling and fault management.
Author
Souham Biswas
Date
2026
Copyright
Copyright (c) 2026 ICARUS Project
Definition in file bsp_error.h.
Enumeration Type Documentation
bsp_status_t
enum bsp_status_t
System error codes.
Enumerator
BSP_OK
No error.
BSP_ERROR
Generic error.
BSP_ERROR_TIMEOUT
Operation timed out.
BSP_ERROR_BUSY
Resource busy.
BSP_ERROR_PARAM
Invalid parameter.
BSP_ERROR_MEMORY
Memory allocation failed.
BSP_ERROR_HARDWARE
Hardware failure.
Definition at line 30 of file bsp_error.h.
Function Documentation
assert_failed()
void assert_failed (uint8_t * file, uint32_t line)
Assert handler with location info.
Parameters
[in] file Source file name
[in] line Line number
Note
Called by assert_param() macro when assertion fails
Error_Handler()
void Error_Handler (void)
System error handler.
Called when an unrecoverable error occurs. Disables interrupts and enters infinite loop.
Warning
This function never returns!
System error handler.
Called when a fatal error is detected that cannot be recovered. Disables all interrupts and enters an infinite loop to prevent further system corruption.
Typical Callers:
HAL initialization failures
Clock configuration errors
Peripheral initialization failures
Stack overflow detection (if enabled)
Warning
This function never returns!
All interrupts are disabled - watchdog will not be serviced
Note
For debugging, set a breakpoint on this function to catch errors
Consider adding LED blink pattern for field diagnosis
Definition at line 50 of file error.c.
Referenced by HAL_I2C_MspInit(), HAL_RTC_MspInit(), HAL_SPI_MspInit(), MX_I2C2_Init(), MX_RTC_Init(), MX_SPI4_Init(), MX_TIM1_Init(), and SystemClock_Config().