ICARUS OS: LSM9DS1_Interrupt_on_threshold
LSM9DS1_Interrupt_on_threshold
LSM9DS1
Functions
int32_t lsm9ds1_xl_trshld_axis_set (const stmdev_ctx_t *ctx, lsm9ds1_xl_trshld_en_t val)
Enable interrupt generation on threshold event.
int32_t lsm9ds1_xl_trshld_axis_get (const stmdev_ctx_t *ctx, lsm9ds1_xl_trshld_en_t *val)
Enable interrupt generation on threshold event.
int32_t lsm9ds1_xl_trshld_set (const stmdev_ctx_t *ctx, uint8_t *buff)
Axis interrupt threshold.
int32_t lsm9ds1_xl_trshld_get (const stmdev_ctx_t *ctx, uint8_t *buff)
Axis interrupt threshold.
int32_t lsm9ds1_xl_trshld_min_sample_set (const stmdev_ctx_t *ctx, uint8_t val)
Enter/exit interrupt duration value.
int32_t lsm9ds1_xl_trshld_min_sample_get (const stmdev_ctx_t *ctx, uint8_t *val)
Enter/exit interrupt duration value.
int32_t lsm9ds1_gy_trshld_src_get (const stmdev_ctx_t *ctx, lsm9ds1_gy_trshld_src_t *val)
Angular rate sensor interrupt on threshold source.
int32_t lsm9ds1_xl_trshld_src_get (const stmdev_ctx_t *ctx, lsm9ds1_xl_trshld_src_t *val)
Accelerometer interrupt on threshold source.
int32_t lsm9ds1_gy_trshld_axis_set (const stmdev_ctx_t *ctx, lsm9ds1_gy_trshld_en_t val)
Enable interrupt generation on threshold event.
int32_t lsm9ds1_gy_trshld_axis_get (const stmdev_ctx_t *ctx, lsm9ds1_gy_trshld_en_t *val)
Enable interrupt generation on threshold event.
int32_t lsm9ds1_gy_trshld_mode_set (const stmdev_ctx_t *ctx, lsm9ds1_dcrm_g_t val)
Decrement or reset counter mode selection.
int32_t lsm9ds1_gy_trshld_mode_get (const stmdev_ctx_t *ctx, lsm9ds1_dcrm_g_t *val)
Decrement or reset counter mode selection.
int32_t lsm9ds1_gy_trshld_x_set (const stmdev_ctx_t *ctx, uint16_t val)
Angular rate sensor interrupt threshold on pitch (X) axis.
int32_t lsm9ds1_gy_trshld_x_get (const stmdev_ctx_t *ctx, uint16_t *val)
Angular rate sensor interrupt threshold on pitch (X) axis.
int32_t lsm9ds1_gy_trshld_y_set (const stmdev_ctx_t *ctx, uint16_t val)
Angular rate sensor interrupt threshold on roll (Y) axis.
int32_t lsm9ds1_gy_trshld_y_get (const stmdev_ctx_t *ctx, uint16_t *val)
Angular rate sensor interrupt threshold on roll (Y) axis.
int32_t lsm9ds1_gy_trshld_z_set (const stmdev_ctx_t *ctx, uint16_t val)
Angular rate sensor interrupt thresholds on yaw (Z) axis.
int32_t lsm9ds1_gy_trshld_z_get (const stmdev_ctx_t *ctx, uint16_t *val)
Angular rate sensor interrupt thresholds on yaw (Z) axis.
int32_t lsm9ds1_gy_trshld_min_sample_set (const stmdev_ctx_t *ctx, uint8_t val)
Enter/exit interrupt duration value.
int32_t lsm9ds1_gy_trshld_min_sample_get (const stmdev_ctx_t *ctx, uint8_t *val)
Enter/exit interrupt duration value.
int32_t lsm9ds1_mag_trshld_axis_set (const stmdev_ctx_t *ctx, lsm9ds1_mag_trshld_axis_t val)
Enable interrupt generation on threshold event.
int32_t lsm9ds1_mag_trshld_axis_get (const stmdev_ctx_t *ctx, lsm9ds1_mag_trshld_axis_t *val)
Enable interrupt generation on threshold event.
int32_t lsm9ds1_mag_trshld_src_get (const stmdev_ctx_t *ctx, lsm9ds1_mag_trshld_src_t *val)
Magnetometer interrupt on threshold source.
int32_t lsm9ds1_mag_trshld_get (const stmdev_ctx_t *ctx, uint8_t *val)
The value is expressed in 15-bit unsigned.
Detailed Description
This section group all the functions concerning the interrupt on threshold configuration
Function Documentation
lsm9ds1_gy_trshld_axis_get()
int32_t lsm9ds1_gy_trshld_axis_get (const stmdev_ctx_t * ctx, lsm9ds1_gy_trshld_en_t * val)
Enable interrupt generation on threshold event.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Enable interrupt generation on gyroscope’s pitch (X) axis low event.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3471 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_CFG_G, lsm9ds1_read_reg(), lsm9ds1_gy_trshld_en_t::xhie_g, lsm9ds1_int_gen_cfg_g_t::xhie_g, lsm9ds1_gy_trshld_en_t::xlie_g, lsm9ds1_int_gen_cfg_g_t::xlie_g, lsm9ds1_gy_trshld_en_t::yhie_g, lsm9ds1_int_gen_cfg_g_t::yhie_g, lsm9ds1_gy_trshld_en_t::ylie_g, lsm9ds1_int_gen_cfg_g_t::ylie_g, lsm9ds1_gy_trshld_en_t::zhie_g, lsm9ds1_int_gen_cfg_g_t::zhie_g, lsm9ds1_gy_trshld_en_t::zlie_g, and lsm9ds1_int_gen_cfg_g_t::zlie_g.
lsm9ds1_gy_trshld_axis_set()
int32_t lsm9ds1_gy_trshld_axis_set (const stmdev_ctx_t * ctx, lsm9ds1_gy_trshld_en_t val)
Enable interrupt generation on threshold event.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Enable interrupt generation on gyroscope’s pitch (X) axis low event.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3438 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_CFG_G, lsm9ds1_read_reg(), lsm9ds1_write_reg(), lsm9ds1_gy_trshld_en_t::xhie_g, lsm9ds1_int_gen_cfg_g_t::xhie_g, lsm9ds1_gy_trshld_en_t::xlie_g, lsm9ds1_int_gen_cfg_g_t::xlie_g, lsm9ds1_gy_trshld_en_t::yhie_g, lsm9ds1_int_gen_cfg_g_t::yhie_g, lsm9ds1_gy_trshld_en_t::ylie_g, lsm9ds1_int_gen_cfg_g_t::ylie_g, lsm9ds1_gy_trshld_en_t::zhie_g, lsm9ds1_int_gen_cfg_g_t::zhie_g, lsm9ds1_gy_trshld_en_t::zlie_g, and lsm9ds1_int_gen_cfg_g_t::zlie_g.
lsm9ds1_gy_trshld_min_sample_get()
int32_t lsm9ds1_gy_trshld_min_sample_get (const stmdev_ctx_t * ctx, uint8_t * val)
Enter/exit interrupt duration value.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of dur_g in reg INT_GEN_DUR_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3807 of file lsm9ds1_reg.c.
References lsm9ds1_int_gen_dur_g_t::dur_g, LSM9DS1_INT_GEN_DUR_G, and lsm9ds1_read_reg().
lsm9ds1_gy_trshld_min_sample_set()
int32_t lsm9ds1_gy_trshld_min_sample_set (const stmdev_ctx_t * ctx, uint8_t val)
Enter/exit interrupt duration value.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of dur_g in reg INT_GEN_DUR_G.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3770 of file lsm9ds1_reg.c.
References lsm9ds1_int_gen_dur_g_t::dur_g, LSM9DS1_INT_GEN_DUR_G, lsm9ds1_read_reg(), lsm9ds1_write_reg(), PROPERTY_DISABLE, PROPERTY_ENABLE, and lsm9ds1_int_gen_dur_g_t::wait_g.
lsm9ds1_gy_trshld_mode_get()
int32_t lsm9ds1_gy_trshld_mode_get (const stmdev_ctx_t * ctx, lsm9ds1_dcrm_g_t * val)
Decrement or reset counter mode selection.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of dcrm_g in reg INT_GEN_THS_XH_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3524 of file lsm9ds1_reg.c.
References lsm9ds1_int_gen_ths_xh_g_t::dcrm_g, LSM9DS1_DECREMENT_MODE, LSM9DS1_INT_GEN_THS_XH_G, lsm9ds1_read_reg(), and LSM9DS1_RESET_MODE.
lsm9ds1_gy_trshld_mode_set()
int32_t lsm9ds1_gy_trshld_mode_set (const stmdev_ctx_t * ctx, lsm9ds1_dcrm_g_t val)
Decrement or reset counter mode selection.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "dcrm_g" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3497 of file lsm9ds1_reg.c.
References lsm9ds1_int_gen_ths_xh_g_t::dcrm_g, LSM9DS1_INT_GEN_THS_XH_G, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_gy_trshld_src_get()
int32_t lsm9ds1_gy_trshld_src_get (const stmdev_ctx_t * ctx, lsm9ds1_gy_trshld_src_t * val)
Angular rate sensor interrupt on threshold source.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Pitch(X)low.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3383 of file lsm9ds1_reg.c.
References lsm9ds1_gy_trshld_src_t::ia_g, lsm9ds1_int_gen_src_g_t::ia_g, LSM9DS1_INT_GEN_SRC_G, lsm9ds1_read_reg(), lsm9ds1_gy_trshld_src_t::xh_g, lsm9ds1_int_gen_src_g_t::xh_g, lsm9ds1_gy_trshld_src_t::xl_g, lsm9ds1_int_gen_src_g_t::xl_g, lsm9ds1_gy_trshld_src_t::yh_g, lsm9ds1_int_gen_src_g_t::yh_g, lsm9ds1_gy_trshld_src_t::yl_g, lsm9ds1_int_gen_src_g_t::yl_g, lsm9ds1_gy_trshld_src_t::zh_g, lsm9ds1_int_gen_src_g_t::zh_g, lsm9ds1_gy_trshld_src_t::zl_g, and lsm9ds1_int_gen_src_g_t::zl_g.
lsm9ds1_gy_trshld_x_get()
int32_t lsm9ds1_gy_trshld_x_get (const stmdev_ctx_t * ctx, uint16_t * val)
Angular rate sensor interrupt threshold on pitch (X) axis.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of ths_g_x in reg INT_GEN_THS_XH_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3599 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_THS_XH_G, LSM9DS1_INT_GEN_THS_XL_G, lsm9ds1_read_reg(), lsm9ds1_int_gen_ths_xh_g_t::ths_g_x, and lsm9ds1_int_gen_ths_xl_g_t::ths_g_x.
lsm9ds1_gy_trshld_x_set()
int32_t lsm9ds1_gy_trshld_x_set (const stmdev_ctx_t * ctx, uint16_t val)
Angular rate sensor interrupt threshold on pitch (X) axis.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of ths_g_x in reg INT_GEN_THS_XH_G.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3559 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_THS_XH_G, LSM9DS1_INT_GEN_THS_XL_G, lsm9ds1_read_reg(), lsm9ds1_write_reg(), lsm9ds1_int_gen_ths_xh_g_t::ths_g_x, and lsm9ds1_int_gen_ths_xl_g_t::ths_g_x.
lsm9ds1_gy_trshld_y_get()
int32_t lsm9ds1_gy_trshld_y_get (const stmdev_ctx_t * ctx, uint16_t * val)
Angular rate sensor interrupt threshold on roll (Y) axis.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of ths_g_y in reg INT_GEN_THS_YH_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3670 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_THS_YH_G, LSM9DS1_INT_GEN_THS_YL_G, lsm9ds1_read_reg(), lsm9ds1_int_gen_ths_yh_g_t::ths_g_y, and lsm9ds1_int_gen_ths_yl_g_t::ths_g_y.
lsm9ds1_gy_trshld_y_set()
int32_t lsm9ds1_gy_trshld_y_set (const stmdev_ctx_t * ctx, uint16_t val)
Angular rate sensor interrupt threshold on roll (Y) axis.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of ths_g_y in reg INT_GEN_THS_YH_G.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3630 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_THS_YH_G, LSM9DS1_INT_GEN_THS_YL_G, lsm9ds1_read_reg(), lsm9ds1_write_reg(), lsm9ds1_int_gen_ths_yh_g_t::ths_g_y, and lsm9ds1_int_gen_ths_yl_g_t::ths_g_y.
lsm9ds1_gy_trshld_z_get()
int32_t lsm9ds1_gy_trshld_z_get (const stmdev_ctx_t * ctx, uint16_t * val)
Angular rate sensor interrupt thresholds on yaw (Z) axis.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of ths_g_z in reg INT_GEN_THS_ZH_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3740 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_THS_ZH_G, LSM9DS1_INT_GEN_THS_ZL_G, lsm9ds1_read_reg(), lsm9ds1_int_gen_ths_zh_g_t::ths_g_z, and lsm9ds1_int_gen_ths_zl_g_t::ths_g_z.
lsm9ds1_gy_trshld_z_set()
int32_t lsm9ds1_gy_trshld_z_set (const stmdev_ctx_t * ctx, uint16_t val)
Angular rate sensor interrupt thresholds on yaw (Z) axis.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of ths_g_z in reg INT_GEN_THS_ZH_G.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3700 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_THS_ZH_G, LSM9DS1_INT_GEN_THS_ZL_G, lsm9ds1_read_reg(), lsm9ds1_write_reg(), lsm9ds1_int_gen_ths_zh_g_t::ths_g_z, and lsm9ds1_int_gen_ths_zl_g_t::ths_g_z.
lsm9ds1_mag_trshld_axis_get()
int32_t lsm9ds1_mag_trshld_axis_get (const stmdev_ctx_t * ctx, lsm9ds1_mag_trshld_axis_t * val)
Enable interrupt generation on threshold event.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Enable interrupt generation on Z-axis. .(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3855 of file lsm9ds1_reg.c.
References LSM9DS1_INT_CFG_M, lsm9ds1_read_reg(), lsm9ds1_int_cfg_m_t::xien, lsm9ds1_mag_trshld_axis_t::xien, lsm9ds1_int_cfg_m_t::yien, lsm9ds1_mag_trshld_axis_t::yien, lsm9ds1_int_cfg_m_t::zien, and lsm9ds1_mag_trshld_axis_t::zien.
lsm9ds1_mag_trshld_axis_set()
int32_t lsm9ds1_mag_trshld_axis_set (const stmdev_ctx_t * ctx, lsm9ds1_mag_trshld_axis_t val)
Enable interrupt generation on threshold event.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Enable interrupt generation on Z-axis. .
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3828 of file lsm9ds1_reg.c.
References LSM9DS1_INT_CFG_M, lsm9ds1_read_reg(), lsm9ds1_write_reg(), lsm9ds1_int_cfg_m_t::xien, lsm9ds1_mag_trshld_axis_t::xien, lsm9ds1_int_cfg_m_t::yien, lsm9ds1_mag_trshld_axis_t::yien, lsm9ds1_int_cfg_m_t::zien, and lsm9ds1_mag_trshld_axis_t::zien.
lsm9ds1_mag_trshld_get()
int32_t lsm9ds1_mag_trshld_get (const stmdev_ctx_t * ctx, uint8_t * val)
The value is expressed in 15-bit unsigned.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Iet the values of "ths" in reg INT_THS_L_M.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3903 of file lsm9ds1_reg.c.
References LSM9DS1_INT_THS_H_M, LSM9DS1_INT_THS_L_M, lsm9ds1_read_reg(), lsm9ds1_int_ths_h_m_t::ths, and lsm9ds1_int_ths_l_m_t::ths.
lsm9ds1_mag_trshld_src_get()
int32_t lsm9ds1_mag_trshld_src_get (const stmdev_ctx_t * ctx, lsm9ds1_mag_trshld_src_t * val)
Magnetometer interrupt on threshold source.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val This bit signals when the interrupt event occurs.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3877 of file lsm9ds1_reg.c.
References lsm9ds1_int_src_m_t::_int, lsm9ds1_mag_trshld_src_t::_int, LSM9DS1_INT_SRC_M, lsm9ds1_read_reg(), lsm9ds1_int_src_m_t::nth_x, lsm9ds1_mag_trshld_src_t::nth_x, lsm9ds1_int_src_m_t::nth_y, lsm9ds1_mag_trshld_src_t::nth_y, lsm9ds1_int_src_m_t::nth_z, lsm9ds1_mag_trshld_src_t::nth_z, lsm9ds1_int_src_m_t::pth_x, lsm9ds1_mag_trshld_src_t::pth_x, lsm9ds1_int_src_m_t::pth_y, lsm9ds1_mag_trshld_src_t::pth_y, lsm9ds1_int_src_m_t::pth_z, and lsm9ds1_mag_trshld_src_t::pth_z.
lsm9ds1_xl_trshld_axis_get()
int32_t lsm9ds1_xl_trshld_axis_get (const stmdev_ctx_t * ctx, lsm9ds1_xl_trshld_en_t * val)
Enable interrupt generation on threshold event.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Enable interrupt generation on accelerometer’s X-axis low event.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3264 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_CFG_XL, lsm9ds1_read_reg(), lsm9ds1_int_gen_cfg_xl_t::xhie_xl, lsm9ds1_xl_trshld_en_t::xhie_xl, lsm9ds1_int_gen_cfg_xl_t::xlie_xl, lsm9ds1_xl_trshld_en_t::xlie_xl, lsm9ds1_int_gen_cfg_xl_t::yhie_xl, lsm9ds1_xl_trshld_en_t::yhie_xl, lsm9ds1_int_gen_cfg_xl_t::ylie_xl, lsm9ds1_xl_trshld_en_t::ylie_xl, lsm9ds1_int_gen_cfg_xl_t::zhie_xl, lsm9ds1_xl_trshld_en_t::zhie_xl, lsm9ds1_int_gen_cfg_xl_t::zlie_xl, and lsm9ds1_xl_trshld_en_t::zlie_xl.
lsm9ds1_xl_trshld_axis_set()
int32_t lsm9ds1_xl_trshld_axis_set (const stmdev_ctx_t * ctx, lsm9ds1_xl_trshld_en_t val)
Enable interrupt generation on threshold event.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Enable interrupt generation on accelerometer’s X-axis low event.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3231 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_CFG_XL, lsm9ds1_read_reg(), lsm9ds1_write_reg(), lsm9ds1_int_gen_cfg_xl_t::xhie_xl, lsm9ds1_xl_trshld_en_t::xhie_xl, lsm9ds1_int_gen_cfg_xl_t::xlie_xl, lsm9ds1_xl_trshld_en_t::xlie_xl, lsm9ds1_int_gen_cfg_xl_t::yhie_xl, lsm9ds1_xl_trshld_en_t::yhie_xl, lsm9ds1_int_gen_cfg_xl_t::ylie_xl, lsm9ds1_xl_trshld_en_t::ylie_xl, lsm9ds1_int_gen_cfg_xl_t::zhie_xl, lsm9ds1_xl_trshld_en_t::zhie_xl, lsm9ds1_int_gen_cfg_xl_t::zlie_xl, and lsm9ds1_xl_trshld_en_t::zlie_xl.
lsm9ds1_xl_trshld_get()
int32_t lsm9ds1_xl_trshld_get (const stmdev_ctx_t * ctx, uint8_t * buff)
Axis interrupt threshold.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3307 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_THS_X_XL, and lsm9ds1_read_reg().
lsm9ds1_xl_trshld_min_sample_get()
int32_t lsm9ds1_xl_trshld_min_sample_get (const stmdev_ctx_t * ctx, uint8_t * val)
Enter/exit interrupt duration value.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of dur_xl in reg INT_GEN_DUR_XL.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3362 of file lsm9ds1_reg.c.
References lsm9ds1_int_gen_dur_xl_t::dur_xl, LSM9DS1_INT_GEN_DUR_XL, and lsm9ds1_read_reg().
lsm9ds1_xl_trshld_min_sample_set()
int32_t lsm9ds1_xl_trshld_min_sample_set (const stmdev_ctx_t * ctx, uint8_t val)
Enter/exit interrupt duration value.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of dur_xl in reg INT_GEN_DUR_XL.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3324 of file lsm9ds1_reg.c.
References lsm9ds1_int_gen_dur_xl_t::dur_xl, LSM9DS1_INT_GEN_DUR_XL, lsm9ds1_read_reg(), lsm9ds1_write_reg(), PROPERTY_DISABLE, PROPERTY_ENABLE, and lsm9ds1_int_gen_dur_xl_t::wait_xl.
lsm9ds1_xl_trshld_set()
int32_t lsm9ds1_xl_trshld_set (const stmdev_ctx_t * ctx, uint8_t * buff)
Axis interrupt threshold.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores data to be write.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3290 of file lsm9ds1_reg.c.
References LSM9DS1_INT_GEN_THS_X_XL, and lsm9ds1_write_reg().
lsm9ds1_xl_trshld_src_get()
int32_t lsm9ds1_xl_trshld_src_get (const stmdev_ctx_t * ctx, lsm9ds1_xl_trshld_src_t * val)
Accelerometer interrupt on threshold source.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Accelerometer’s X low. event.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 3410 of file lsm9ds1_reg.c.
References lsm9ds1_int_gen_src_xl_t::ia_xl, lsm9ds1_xl_trshld_src_t::ia_xl, LSM9DS1_INT_GEN_SRC_XL, lsm9ds1_read_reg(), lsm9ds1_int_gen_src_xl_t::xh_xl, lsm9ds1_xl_trshld_src_t::xh_xl, lsm9ds1_int_gen_src_xl_t::xl_xl, lsm9ds1_xl_trshld_src_t::xl_xl, lsm9ds1_int_gen_src_xl_t::yh_xl, lsm9ds1_xl_trshld_src_t::yh_xl, lsm9ds1_int_gen_src_xl_t::yl_xl, lsm9ds1_xl_trshld_src_t::yl_xl, lsm9ds1_int_gen_src_xl_t::zh_xl, lsm9ds1_xl_trshld_src_t::zh_xl, lsm9ds1_int_gen_src_xl_t::zl_xl, and lsm9ds1_xl_trshld_src_t::zl_xl.