ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): LSM9DS1_Serial_interface
LSM9DS1_Serial_interface
LSM9DS1
Functions
int32_t lsm9ds1_auto_increment_set (const stmdev_ctx_t *ctx, uint8_t val)
Register address automatically incremented during a multiple byte access with a serial interface.
int32_t lsm9ds1_auto_increment_get (const stmdev_ctx_t *ctx, uint8_t *val)
Register address automatically incremented during a multiple byte access with a serial interface.
int32_t lsm9ds1_spi_mode_set (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, lsm9ds1_sim_t val)
SPI Serial Interface Mode selection.
int32_t lsm9ds1_spi_mode_get (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, lsm9ds1_sim_t *val)
SPI Serial Interface Mode selection.
int32_t lsm9ds1_i2c_interface_set (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, lsm9ds1_i2c_dis_t val)
Enable / Disable I2C interface.
int32_t lsm9ds1_i2c_interface_get (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, lsm9ds1_i2c_dis_t *val)
Enable / Disable I2C interface.
Detailed Description
This section groups all the functions concerning main serial interface management (not auxiliary)
Function Documentation
lsm9ds1_auto_increment_get()
int32_t lsm9ds1_auto_increment_get (const stmdev_ctx_t * ctx, uint8_t * val)
Register address automatically incremented during a multiple byte access with a serial interface.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of if_add_inc in reg CTRL_REG8.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2516 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg8_t::if_add_inc, LSM9DS1_CTRL_REG8, and lsm9ds1_read_reg().
lsm9ds1_auto_increment_set()
int32_t lsm9ds1_auto_increment_set (const stmdev_ctx_t * ctx, uint8_t val)
Register address automatically incremented during a multiple byte access with a serial interface.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "if_add_inc" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2491 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg8_t::if_add_inc, LSM9DS1_CTRL_REG8, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_i2c_interface_get()
int32_t lsm9ds1_i2c_interface_get (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, lsm9ds1_i2c_dis_t * val)
Enable / Disable I2C interface.
[get]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Get the values of i2c_disable in reg CTRL_REG9.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2666 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg3_m_t::i2c_disable, lsm9ds1_ctrl_reg9_t::i2c_disable, LSM9DS1_CTRL_REG3_M, LSM9DS1_CTRL_REG9, LSM9DS1_I2C_DISABLE, LSM9DS1_I2C_ENABLE, and lsm9ds1_read_reg().
lsm9ds1_i2c_interface_set()
int32_t lsm9ds1_i2c_interface_set (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, lsm9ds1_i2c_dis_t val)
Enable / Disable I2C interface.
[set]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Change the values of "i2c_disable" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2623 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg3_m_t::i2c_disable, lsm9ds1_ctrl_reg9_t::i2c_disable, LSM9DS1_CTRL_REG3_M, LSM9DS1_CTRL_REG9, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_spi_mode_get()
int32_t lsm9ds1_spi_mode_get (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, lsm9ds1_sim_t * val)
SPI Serial Interface Mode selection.
[get]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Get the values of sim in reg CTRL_REG8.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2579 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG3_M, LSM9DS1_CTRL_REG8, lsm9ds1_read_reg(), LSM9DS1_SPI_3_WIRE, LSM9DS1_SPI_4_WIRE, lsm9ds1_ctrl_reg3_m_t::sim, and lsm9ds1_ctrl_reg8_t::sim.
lsm9ds1_spi_mode_set()
int32_t lsm9ds1_spi_mode_set (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, lsm9ds1_sim_t val)
SPI Serial Interface Mode selection.
[set]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Change the values of "sim" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2536 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG3_M, LSM9DS1_CTRL_REG8, lsm9ds1_read_reg(), lsm9ds1_write_reg(), lsm9ds1_ctrl_reg3_m_t::sim, and lsm9ds1_ctrl_reg8_t::sim.