ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): LSM9DS1_Self_test
LSM9DS1_Self_test
LSM9DS1
Functions
int32_t lsm9ds1_xl_self_test_set (const stmdev_ctx_t *ctx, uint8_t val)
Enable/disable self-test mode for accelerometer.
int32_t lsm9ds1_xl_self_test_get (const stmdev_ctx_t *ctx, uint8_t *val)
Enable/disable self-test mode for accelerometer.
int32_t lsm9ds1_gy_self_test_set (const stmdev_ctx_t *ctx, uint8_t val)
Enable/disable self-test mode for gyroscope.
int32_t lsm9ds1_gy_self_test_get (const stmdev_ctx_t *ctx, uint8_t *val)
Enable/disable self-test mode for gyroscope.
int32_t lsm9ds1_mag_self_test_set (const stmdev_ctx_t *ctx, uint8_t val)
Enable/disable self-test mode for magnatic sensor.
int32_t lsm9ds1_mag_self_test_get (const stmdev_ctx_t *ctx, uint8_t *val)
Enable/disable self-test mode for magnatic sensor.
Detailed Description
This section groups all the functions that manage self test configuration
Function Documentation
lsm9ds1_gy_self_test_get()
int32_t lsm9ds1_gy_self_test_get (const stmdev_ctx_t * ctx, uint8_t * val)
Enable/disable self-test mode for gyroscope.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of st_g in reg CTRL_REG10.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4700 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG10, lsm9ds1_read_reg(), and lsm9ds1_ctrl_reg10_t::st_g.
lsm9ds1_gy_self_test_set()
int32_t lsm9ds1_gy_self_test_set (const stmdev_ctx_t * ctx, uint8_t val)
Enable/disable self-test mode for gyroscope.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of st_g in reg CTRL_REG10.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4674 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG10, lsm9ds1_read_reg(), lsm9ds1_write_reg(), and lsm9ds1_ctrl_reg10_t::st_g.
lsm9ds1_mag_self_test_get()
int32_t lsm9ds1_mag_self_test_get (const stmdev_ctx_t * ctx, uint8_t * val)
Enable/disable self-test mode for magnatic sensor.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of st in reg CTRL_REG1_M.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4746 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG1_M, lsm9ds1_read_reg(), and lsm9ds1_ctrl_reg1_m_t::st.
lsm9ds1_mag_self_test_set()
int32_t lsm9ds1_mag_self_test_set (const stmdev_ctx_t * ctx, uint8_t val)
Enable/disable self-test mode for magnatic sensor.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of st in reg CTRL_REG1_M.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4720 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG1_M, lsm9ds1_read_reg(), lsm9ds1_write_reg(), and lsm9ds1_ctrl_reg1_m_t::st.
lsm9ds1_xl_self_test_get()
int32_t lsm9ds1_xl_self_test_get (const stmdev_ctx_t * ctx, uint8_t * val)
Enable/disable self-test mode for accelerometer.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of st_xl in reg CTRL_REG10.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4654 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG10, lsm9ds1_read_reg(), and lsm9ds1_ctrl_reg10_t::st_xl.
lsm9ds1_xl_self_test_set()
int32_t lsm9ds1_xl_self_test_set (const stmdev_ctx_t * ctx, uint8_t val)
Enable/disable self-test mode for accelerometer.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of st_xl in reg CTRL_REG10.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4628 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG10, lsm9ds1_read_reg(), lsm9ds1_write_reg(), and lsm9ds1_ctrl_reg10_t::st_xl.