ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): LSM9DS1_Filters
LSM9DS1_Filters
LSM9DS1
Functions
int32_t lsm9ds1_gy_filter_reference_set (const stmdev_ctx_t *ctx, uint8_t *buff)
Reference value for gyroscope’s digital high-pass filter.
int32_t lsm9ds1_gy_filter_reference_get (const stmdev_ctx_t *ctx, uint8_t *buff)
Reference value for gyroscope’s digital high-pass filter.
int32_t lsm9ds1_gy_filter_lp_bandwidth_set (const stmdev_ctx_t *ctx, lsm9ds1_gy_lp_bw_t val)
Gyroscope lowpass filter bandwidth selection.
int32_t lsm9ds1_gy_filter_lp_bandwidth_get (const stmdev_ctx_t *ctx, lsm9ds1_gy_lp_bw_t *val)
Gyroscope lowpass filter bandwidth selection.
int32_t lsm9ds1_gy_filter_out_path_set (const stmdev_ctx_t *ctx, lsm9ds1_gy_out_path_t val)
Gyro output filter path configuration.
int32_t lsm9ds1_gy_filter_out_path_get (const stmdev_ctx_t *ctx, lsm9ds1_gy_out_path_t *val)
Gyro output filter path configuration.
int32_t lsm9ds1_gy_filter_int_path_set (const stmdev_ctx_t *ctx, lsm9ds1_gy_int_path_t val)
Gyro interrupt filter path configuration.
int32_t lsm9ds1_gy_filter_int_path_get (const stmdev_ctx_t *ctx, lsm9ds1_gy_int_path_t *val)
Gyro interrupt filter path configuration.
int32_t lsm9ds1_gy_filter_hp_bandwidth_set (const stmdev_ctx_t *ctx, lsm9ds1_gy_hp_bw_t val)
Gyroscope high-pass filter bandwidth selection.
int32_t lsm9ds1_gy_filter_hp_bandwidth_get (const stmdev_ctx_t *ctx, lsm9ds1_gy_hp_bw_t *val)
Gyroscope high-pass filter bandwidth selection.
int32_t lsm9ds1_xl_filter_aalias_bandwidth_set (const stmdev_ctx_t *ctx, lsm9ds1_xl_aa_bw_t val)
Configure accelerometer anti aliasing filter.
int32_t lsm9ds1_xl_filter_aalias_bandwidth_get (const stmdev_ctx_t *ctx, lsm9ds1_xl_aa_bw_t *val)
Configure accelerometer anti aliasing filter.
int32_t lsm9ds1_xl_filter_int_path_set (const stmdev_ctx_t *ctx, lsm9ds1_xl_hp_path_t val)
Configure HP accelerometer filter.
int32_t lsm9ds1_xl_filter_int_path_get (const stmdev_ctx_t *ctx, lsm9ds1_xl_hp_path_t *val)
int32_t lsm9ds1_xl_filter_out_path_set (const stmdev_ctx_t *ctx, lsm9ds1_xl_out_path_t val)
Accelerometer output filter path configuration.
int32_t lsm9ds1_xl_filter_out_path_get (const stmdev_ctx_t *ctx, lsm9ds1_xl_out_path_t *val)
Accelerometer output filter path configuration.
int32_t lsm9ds1_xl_filter_lp_bandwidth_set (const stmdev_ctx_t *ctx, lsm9ds1_xl_lp_bw_t val)
Accelerometer digital filter low pass cutoff frequency selection.
int32_t lsm9ds1_xl_filter_lp_bandwidth_get (const stmdev_ctx_t *ctx, lsm9ds1_xl_lp_bw_t *val)
Accelerometer digital filter low pass cutoff frequency selection.
int32_t lsm9ds1_xl_filter_hp_bandwidth_set (const stmdev_ctx_t *ctx, lsm9ds1_xl_hp_bw_t val)
Accelerometer digital filter high pass cutoff frequency selection.
int32_t lsm9ds1_xl_filter_hp_bandwidth_get (const stmdev_ctx_t *ctx, lsm9ds1_xl_hp_bw_t *val)
Accelerometer digital filter high pass cutoff frequency selection.
int32_t lsm9ds1_filter_settling_mask_set (const stmdev_ctx_t *ctx, uint8_t val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends.
int32_t lsm9ds1_filter_settling_mask_get (const stmdev_ctx_t *ctx, uint8_t *val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends.
Detailed Description
This section group all the functions concerning the filters configuration
Function Documentation
lsm9ds1_filter_settling_mask_get()
int32_t lsm9ds1_filter_settling_mask_get (const stmdev_ctx_t * ctx, uint8_t * val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of drdy_mask_bit in reg CTRL_REG9.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2457 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg9_t::drdy_mask_bit, LSM9DS1_CTRL_REG9, and lsm9ds1_read_reg().
lsm9ds1_filter_settling_mask_set()
int32_t lsm9ds1_filter_settling_mask_set (const stmdev_ctx_t * ctx, uint8_t val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of drdy_mask_bit in reg CTRL_REG9.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2432 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg9_t::drdy_mask_bit, LSM9DS1_CTRL_REG9, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_gy_filter_hp_bandwidth_get()
int32_t lsm9ds1_gy_filter_hp_bandwidth_get (const stmdev_ctx_t * ctx, lsm9ds1_gy_hp_bw_t * val)
Gyroscope high-pass filter bandwidth selection.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of hpcf_g in reg CTRL_REG3_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2017 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg3_g_t::hpcf_g, LSM9DS1_CTRL_REG3_G, LSM9DS1_HP_EXTREME, LSM9DS1_HP_HIGH, LSM9DS1_HP_LIGHT, LSM9DS1_HP_LOW, LSM9DS1_HP_MEDIUM, LSM9DS1_HP_STRONG, LSM9DS1_HP_ULTRA_HIGH, LSM9DS1_HP_ULTRA_LIGHT, LSM9DS1_HP_ULTRA_LOW, LSM9DS1_HP_ULTRA_STRONG, and lsm9ds1_read_reg().
lsm9ds1_gy_filter_hp_bandwidth_set()
int32_t lsm9ds1_gy_filter_hp_bandwidth_set (const stmdev_ctx_t * ctx, lsm9ds1_gy_hp_bw_t val)
Gyroscope high-pass filter bandwidth selection.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "hpcf_g" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1990 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg3_g_t::hpcf_g, LSM9DS1_CTRL_REG3_G, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_gy_filter_int_path_get()
int32_t lsm9ds1_gy_filter_int_path_get (const stmdev_ctx_t * ctx, lsm9ds1_gy_int_path_t * val)
Gyro interrupt filter path configuration.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of int_sel in reg CTRL_REG2_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1940 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg3_g_t::hp_en, lsm9ds1_ctrl_reg2_g_t::int_sel, LSM9DS1_CTRL_REG2_G, LSM9DS1_CTRL_REG3_G, LSM9DS1_LPF1_HPF_INT, LSM9DS1_LPF1_HPF_LPF2_INT, LSM9DS1_LPF1_INT, LSM9DS1_LPF1_LPF2_INT, and lsm9ds1_read_reg().
lsm9ds1_gy_filter_int_path_set()
int32_t lsm9ds1_gy_filter_int_path_set (const stmdev_ctx_t * ctx, lsm9ds1_gy_int_path_t val)
Gyro interrupt filter path configuration.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "int_sel" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1899 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg3_g_t::hp_en, lsm9ds1_ctrl_reg2_g_t::int_sel, LSM9DS1_CTRL_REG2_G, LSM9DS1_CTRL_REG3_G, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_gy_filter_lp_bandwidth_get()
int32_t lsm9ds1_gy_filter_lp_bandwidth_get (const stmdev_ctx_t * ctx, lsm9ds1_gy_lp_bw_t * val)
Gyroscope lowpass filter bandwidth selection.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of bw_g in reg CTRL_REG1_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1765 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg1_g_t::bw_g, LSM9DS1_CTRL_REG1_G, LSM9DS1_LP_LIGHT, LSM9DS1_LP_MEDIUM, LSM9DS1_LP_STRONG, LSM9DS1_LP_ULTRA_LIGHT, and lsm9ds1_read_reg().
lsm9ds1_gy_filter_lp_bandwidth_set()
int32_t lsm9ds1_gy_filter_lp_bandwidth_set (const stmdev_ctx_t * ctx, lsm9ds1_gy_lp_bw_t val)
Gyroscope lowpass filter bandwidth selection.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "bw_g" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1738 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg1_g_t::bw_g, LSM9DS1_CTRL_REG1_G, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_gy_filter_out_path_get()
int32_t lsm9ds1_gy_filter_out_path_get (const stmdev_ctx_t * ctx, lsm9ds1_gy_out_path_t * val)
Gyro output filter path configuration.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of out_sel in reg CTRL_REG2_G.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1849 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg3_g_t::hp_en, LSM9DS1_CTRL_REG2_G, LSM9DS1_CTRL_REG3_G, LSM9DS1_LPF1_HPF_LPF2_OUT, LSM9DS1_LPF1_HPF_OUT, LSM9DS1_LPF1_LPF2_OUT, LSM9DS1_LPF1_OUT, lsm9ds1_read_reg(), and lsm9ds1_ctrl_reg2_g_t::out_sel.
lsm9ds1_gy_filter_out_path_set()
int32_t lsm9ds1_gy_filter_out_path_set (const stmdev_ctx_t * ctx, lsm9ds1_gy_out_path_t val)
Gyro output filter path configuration.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "out_sel" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1808 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg3_g_t::hp_en, LSM9DS1_CTRL_REG2_G, LSM9DS1_CTRL_REG3_G, lsm9ds1_read_reg(), lsm9ds1_write_reg(), and lsm9ds1_ctrl_reg2_g_t::out_sel.
lsm9ds1_gy_filter_reference_get()
int32_t lsm9ds1_gy_filter_reference_get (const stmdev_ctx_t * ctx, uint8_t * buff)
Reference value for gyroscope’s digital high-pass filter.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1720 of file lsm9ds1_reg.c.
References lsm9ds1_read_reg(), and LSM9DS1_REFERENCE_G.
lsm9ds1_gy_filter_reference_set()
int32_t lsm9ds1_gy_filter_reference_set (const stmdev_ctx_t * ctx, uint8_t * buff)
Reference value for gyroscope’s digital high-pass filter.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores data to be write.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1702 of file lsm9ds1_reg.c.
References LSM9DS1_REFERENCE_G, and lsm9ds1_write_reg().
lsm9ds1_xl_filter_aalias_bandwidth_get()
int32_t lsm9ds1_xl_filter_aalias_bandwidth_get (const stmdev_ctx_t * ctx, lsm9ds1_xl_aa_bw_t * val)
Configure accelerometer anti aliasing filter.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of bw_xl in reg CTRL_REG6_XL.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2112 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg6_xl_t::bw_scal_odr, lsm9ds1_ctrl_reg6_xl_t::bw_xl, LSM9DS1_105Hz, LSM9DS1_211Hz, LSM9DS1_408Hz, LSM9DS1_50Hz, LSM9DS1_AUTO, LSM9DS1_CTRL_REG6_XL, and lsm9ds1_read_reg().
lsm9ds1_xl_filter_aalias_bandwidth_set()
int32_t lsm9ds1_xl_filter_aalias_bandwidth_set (const stmdev_ctx_t * ctx, lsm9ds1_xl_aa_bw_t val)
Configure accelerometer anti aliasing filter.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "bw_xl" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2084 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg6_xl_t::bw_scal_odr, lsm9ds1_ctrl_reg6_xl_t::bw_xl, LSM9DS1_CTRL_REG6_XL, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_xl_filter_hp_bandwidth_get()
int32_t lsm9ds1_xl_filter_hp_bandwidth_get (const stmdev_ctx_t * ctx, lsm9ds1_xl_hp_bw_t * val)
Accelerometer digital filter high pass cutoff frequency selection.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of dcf in reg CTRL_REG7_XL.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2389 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg7_xl_t::dcf, LSM9DS1_CTRL_REG7_XL, LSM9DS1_HP_ODR_DIV_100, LSM9DS1_HP_ODR_DIV_400, LSM9DS1_HP_ODR_DIV_50, LSM9DS1_HP_ODR_DIV_9, and lsm9ds1_read_reg().
lsm9ds1_xl_filter_hp_bandwidth_set()
int32_t lsm9ds1_xl_filter_hp_bandwidth_set (const stmdev_ctx_t * ctx, lsm9ds1_xl_hp_bw_t val)
Accelerometer digital filter high pass cutoff frequency selection.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "dcf" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2361 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg7_xl_t::dcf, LSM9DS1_CTRL_REG7_XL, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_xl_filter_int_path_get()
int32_t lsm9ds1_xl_filter_int_path_get (const stmdev_ctx_t * ctx, lsm9ds1_xl_hp_path_t * val)
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of hpis1 in reg CTRL_REG7_XL.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2186 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg7_xl_t::hpis1, LSM9DS1_CTRL_REG7_XL, LSM9DS1_HP_DIS, LSM9DS1_HP_EN, and lsm9ds1_read_reg().
lsm9ds1_xl_filter_int_path_set()
int32_t lsm9ds1_xl_filter_int_path_set (const stmdev_ctx_t * ctx, lsm9ds1_xl_hp_path_t val)
Configure HP accelerometer filter.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "hpis1" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2159 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg7_xl_t::hpis1, LSM9DS1_CTRL_REG7_XL, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_xl_filter_lp_bandwidth_get()
int32_t lsm9ds1_xl_filter_lp_bandwidth_get (const stmdev_ctx_t * ctx, lsm9ds1_xl_lp_bw_t * val)
Accelerometer digital filter low pass cutoff frequency selection.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of dcf in reg CTRL_REG7_XL.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2313 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg7_xl_t::dcf, lsm9ds1_ctrl_reg7_xl_t::hr, LSM9DS1_CTRL_REG7_XL, LSM9DS1_LP_DISABLE, LSM9DS1_LP_ODR_DIV_100, LSM9DS1_LP_ODR_DIV_400, LSM9DS1_LP_ODR_DIV_50, LSM9DS1_LP_ODR_DIV_9, and lsm9ds1_read_reg().
lsm9ds1_xl_filter_lp_bandwidth_set()
int32_t lsm9ds1_xl_filter_lp_bandwidth_set (const stmdev_ctx_t * ctx, lsm9ds1_xl_lp_bw_t val)
Accelerometer digital filter low pass cutoff frequency selection.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "dcf" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2284 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg7_xl_t::dcf, lsm9ds1_ctrl_reg7_xl_t::hr, LSM9DS1_CTRL_REG7_XL, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_xl_filter_out_path_get()
int32_t lsm9ds1_xl_filter_out_path_get (const stmdev_ctx_t * ctx, lsm9ds1_xl_out_path_t * val)
Accelerometer output filter path configuration.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fds in reg CTRL_REG7_XL.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2248 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg7_xl_t::fds, LSM9DS1_CTRL_REG7_XL, LSM9DS1_HP_OUT, LSM9DS1_LP_OUT, and lsm9ds1_read_reg().
lsm9ds1_xl_filter_out_path_set()
int32_t lsm9ds1_xl_filter_out_path_set (const stmdev_ctx_t * ctx, lsm9ds1_xl_out_path_t val)
Accelerometer output filter path configuration.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "fds" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 2221 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg7_xl_t::fds, LSM9DS1_CTRL_REG7_XL, lsm9ds1_read_reg(), and lsm9ds1_write_reg().