ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): LSM9DS1_Interfaces_Functions
LSM9DS1_Interfaces_Functions
LSM9DS1
This section provide a set of functions used to read and write a generic register of the device.
Functions
int32_t lsm9ds1_read_reg (const stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Read generic device register.
int32_t lsm9ds1_write_reg (const stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Write generic device register.
Detailed Description
This section provide a set of functions used to read and write a generic register of the device.
MANDATORY: return 0 -> no Error.
Function Documentation
lsm9ds1_read_reg()
int32_t lsm9ds1_read_reg (const stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Read generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to read
data pointer to buffer that store the data read(ptr)
len number of consecutive register to read
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 49 of file lsm9ds1_reg.c.
References stmdev_ctx_t::handle, and stmdev_ctx_t::read_reg.
Referenced by lsm9ds1_6d_mode_get(), lsm9ds1_6d_mode_set(), lsm9ds1_6d_src_get(), lsm9ds1_6d_threshold_get(), lsm9ds1_acceleration_raw_get(), lsm9ds1_act_duration_get(), lsm9ds1_act_mode_get(), lsm9ds1_act_mode_set(), lsm9ds1_act_src_get(), lsm9ds1_act_threshold_get(), lsm9ds1_act_threshold_set(), lsm9ds1_angular_rate_raw_get(), lsm9ds1_auto_increment_get(), lsm9ds1_auto_increment_set(), lsm9ds1_block_data_update_get(), lsm9ds1_block_data_update_set(), lsm9ds1_dev_boot_get(), lsm9ds1_dev_boot_set(), lsm9ds1_dev_data_format_get(), lsm9ds1_dev_data_format_set(), lsm9ds1_dev_id_get(), lsm9ds1_dev_reset_get(), lsm9ds1_dev_reset_set(), lsm9ds1_dev_status_get(), lsm9ds1_fifo_data_level_get(), lsm9ds1_fifo_full_flag_get(), lsm9ds1_fifo_mode_get(), lsm9ds1_fifo_mode_set(), lsm9ds1_fifo_ovr_flag_get(), lsm9ds1_fifo_stop_on_wtm_get(), lsm9ds1_fifo_stop_on_wtm_set(), lsm9ds1_fifo_temp_batch_get(), lsm9ds1_fifo_temp_batch_set(), lsm9ds1_fifo_watermark_get(), lsm9ds1_fifo_watermark_set(), lsm9ds1_fifo_wtm_flag_get(), lsm9ds1_filter_settling_mask_get(), lsm9ds1_filter_settling_mask_set(), lsm9ds1_gy_axis_get(), lsm9ds1_gy_axis_set(), lsm9ds1_gy_filter_hp_bandwidth_get(), lsm9ds1_gy_filter_hp_bandwidth_set(), lsm9ds1_gy_filter_int_path_get(), lsm9ds1_gy_filter_int_path_set(), lsm9ds1_gy_filter_lp_bandwidth_get(), lsm9ds1_gy_filter_lp_bandwidth_set(), lsm9ds1_gy_filter_out_path_get(), lsm9ds1_gy_filter_out_path_set(), lsm9ds1_gy_filter_reference_get(), lsm9ds1_gy_flag_data_ready_get(), lsm9ds1_gy_full_scale_get(), lsm9ds1_gy_full_scale_set(), lsm9ds1_gy_orient_get(), lsm9ds1_gy_orient_set(), lsm9ds1_gy_self_test_get(), lsm9ds1_gy_self_test_set(), lsm9ds1_gy_trshld_axis_get(), lsm9ds1_gy_trshld_axis_set(), lsm9ds1_gy_trshld_min_sample_get(), lsm9ds1_gy_trshld_min_sample_set(), lsm9ds1_gy_trshld_mode_get(), lsm9ds1_gy_trshld_mode_set(), lsm9ds1_gy_trshld_src_get(), lsm9ds1_gy_trshld_x_get(), lsm9ds1_gy_trshld_x_set(), lsm9ds1_gy_trshld_y_get(), lsm9ds1_gy_trshld_y_set(), lsm9ds1_gy_trshld_z_get(), lsm9ds1_gy_trshld_z_set(), lsm9ds1_i2c_interface_get(), lsm9ds1_i2c_interface_set(), lsm9ds1_imu_data_rate_get(), lsm9ds1_imu_data_rate_set(), lsm9ds1_mag_data_rate_get(), lsm9ds1_mag_data_rate_set(), lsm9ds1_mag_flag_data_ready_get(), lsm9ds1_mag_full_scale_get(), lsm9ds1_mag_full_scale_set(), lsm9ds1_mag_offset_get(), lsm9ds1_mag_self_test_get(), lsm9ds1_mag_self_test_set(), lsm9ds1_mag_trshld_axis_get(), lsm9ds1_mag_trshld_axis_set(), lsm9ds1_mag_trshld_get(), lsm9ds1_mag_trshld_src_get(), lsm9ds1_magnetic_overflow_get(), lsm9ds1_magnetic_raw_get(), lsm9ds1_pin_int1_route_get(), lsm9ds1_pin_int1_route_set(), lsm9ds1_pin_int2_route_get(), lsm9ds1_pin_int2_route_set(), lsm9ds1_pin_int_m_route_get(), lsm9ds1_pin_int_m_route_set(), lsm9ds1_pin_logic_get(), lsm9ds1_pin_logic_set(), lsm9ds1_pin_mode_get(), lsm9ds1_pin_mode_set(), lsm9ds1_pin_notification_get(), lsm9ds1_pin_notification_set(), lsm9ds1_pin_polarity_get(), lsm9ds1_pin_polarity_set(), lsm9ds1_spi_mode_get(), lsm9ds1_spi_mode_set(), lsm9ds1_temp_flag_data_ready_get(), lsm9ds1_temperature_raw_get(), lsm9ds1_xl_axis_get(), lsm9ds1_xl_axis_set(), lsm9ds1_xl_decimation_get(), lsm9ds1_xl_decimation_set(), lsm9ds1_xl_filter_aalias_bandwidth_get(), lsm9ds1_xl_filter_aalias_bandwidth_set(), lsm9ds1_xl_filter_hp_bandwidth_get(), lsm9ds1_xl_filter_hp_bandwidth_set(), lsm9ds1_xl_filter_int_path_get(), lsm9ds1_xl_filter_int_path_set(), lsm9ds1_xl_filter_lp_bandwidth_get(), lsm9ds1_xl_filter_lp_bandwidth_set(), lsm9ds1_xl_filter_out_path_get(), lsm9ds1_xl_filter_out_path_set(), lsm9ds1_xl_flag_data_ready_get(), lsm9ds1_xl_full_scale_get(), lsm9ds1_xl_full_scale_set(), lsm9ds1_xl_self_test_get(), lsm9ds1_xl_self_test_set(), lsm9ds1_xl_trshld_axis_get(), lsm9ds1_xl_trshld_axis_set(), lsm9ds1_xl_trshld_get(), lsm9ds1_xl_trshld_min_sample_get(), lsm9ds1_xl_trshld_min_sample_set(), and lsm9ds1_xl_trshld_src_get().
lsm9ds1_write_reg()
int32_t lsm9ds1_write_reg (const stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Write generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to write
data pointer to data to write in register reg(ptr)
len number of consecutive register to write
Return values
interface status (MANDATORY: return 0 -> no Error)
Definition at line 75 of file lsm9ds1_reg.c.
References stmdev_ctx_t::handle, and stmdev_ctx_t::write_reg.
Referenced by lsm9ds1_6d_mode_set(), lsm9ds1_6d_threshold_set(), lsm9ds1_act_duration_set(), lsm9ds1_act_mode_set(), lsm9ds1_act_threshold_set(), lsm9ds1_auto_increment_set(), lsm9ds1_block_data_update_set(), lsm9ds1_dev_boot_set(), lsm9ds1_dev_data_format_set(), lsm9ds1_dev_reset_set(), lsm9ds1_fifo_mode_set(), lsm9ds1_fifo_stop_on_wtm_set(), lsm9ds1_fifo_temp_batch_set(), lsm9ds1_fifo_watermark_set(), lsm9ds1_filter_settling_mask_set(), lsm9ds1_gy_axis_set(), lsm9ds1_gy_filter_hp_bandwidth_set(), lsm9ds1_gy_filter_int_path_set(), lsm9ds1_gy_filter_lp_bandwidth_set(), lsm9ds1_gy_filter_out_path_set(), lsm9ds1_gy_filter_reference_set(), lsm9ds1_gy_full_scale_set(), lsm9ds1_gy_orient_set(), lsm9ds1_gy_self_test_set(), lsm9ds1_gy_trshld_axis_set(), lsm9ds1_gy_trshld_min_sample_set(), lsm9ds1_gy_trshld_mode_set(), lsm9ds1_gy_trshld_x_set(), lsm9ds1_gy_trshld_y_set(), lsm9ds1_gy_trshld_z_set(), lsm9ds1_i2c_interface_set(), lsm9ds1_imu_data_rate_set(), lsm9ds1_mag_data_rate_set(), lsm9ds1_mag_full_scale_set(), lsm9ds1_mag_offset_set(), lsm9ds1_mag_self_test_set(), lsm9ds1_mag_trshld_axis_set(), lsm9ds1_pin_int1_route_set(), lsm9ds1_pin_int2_route_set(), lsm9ds1_pin_int_m_route_set(), lsm9ds1_pin_logic_set(), lsm9ds1_pin_mode_set(), lsm9ds1_pin_notification_set(), lsm9ds1_pin_polarity_set(), lsm9ds1_spi_mode_set(), lsm9ds1_xl_axis_set(), lsm9ds1_xl_decimation_set(), lsm9ds1_xl_filter_aalias_bandwidth_set(), lsm9ds1_xl_filter_hp_bandwidth_set(), lsm9ds1_xl_filter_int_path_set(), lsm9ds1_xl_filter_lp_bandwidth_set(), lsm9ds1_xl_filter_out_path_set(), lsm9ds1_xl_full_scale_set(), lsm9ds1_xl_self_test_set(), lsm9ds1_xl_trshld_axis_set(), lsm9ds1_xl_trshld_min_sample_set(), and lsm9ds1_xl_trshld_set().