ICARUS OS: LSM9DS1_Dataoutput
LSM9DS1_Dataoutput
LSM9DS1
Functions
int32_t lsm9ds1_temperature_raw_get (const stmdev_ctx_t *ctx, int16_t *val)
Temperature data output register (r).
int32_t lsm9ds1_angular_rate_raw_get (const stmdev_ctx_t *ctx, int16_t *val)
Angular rate sensor.
int32_t lsm9ds1_acceleration_raw_get (const stmdev_ctx_t *ctx, int16_t *val)
Linear acceleration output register.
int32_t lsm9ds1_magnetic_raw_get (const stmdev_ctx_t *ctx, int16_t *val)
Magnetic sensor.
int32_t lsm9ds1_magnetic_overflow_get (const stmdev_ctx_t *ctx, uint8_t *val)
Internal measurement range overflow on magnetic value.
Detailed Description
This section groups all the data output functions.
Function Documentation
lsm9ds1_acceleration_raw_get()
int32_t lsm9ds1_acceleration_raw_get (const stmdev_ctx_t * ctx, int16_t * val)
Linear acceleration output register.
The value is expressed as a 16-bit word in two’s complement.[get]
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1322 of file lsm9ds1_reg.c.
References LSM9DS1_OUT_X_L_XL, and lsm9ds1_read_reg().
lsm9ds1_angular_rate_raw_get()
int32_t lsm9ds1_angular_rate_raw_get (const stmdev_ctx_t * ctx, int16_t * val)
Angular rate sensor.
The value is expressed as a 16-bit word in two’s complement.[get]
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1297 of file lsm9ds1_reg.c.
References LSM9DS1_OUT_X_L_G, and lsm9ds1_read_reg().
lsm9ds1_magnetic_overflow_get()
int32_t lsm9ds1_magnetic_overflow_get (const stmdev_ctx_t * ctx, uint8_t * val)
Internal measurement range overflow on magnetic value.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Iet the values of "mroi" in reg INT_SRC_M.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1371 of file lsm9ds1_reg.c.
References LSM9DS1_INT_SRC_M, lsm9ds1_read_reg(), and lsm9ds1_int_src_m_t::mroi.
lsm9ds1_magnetic_raw_get()
int32_t lsm9ds1_magnetic_raw_get (const stmdev_ctx_t * ctx, int16_t * val)
Magnetic sensor.
The value is expressed as a 16-bit word in two’s complement.[get]
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1347 of file lsm9ds1_reg.c.
References LSM9DS1_OUT_X_L_M, and lsm9ds1_read_reg().
lsm9ds1_temperature_raw_get()
int32_t lsm9ds1_temperature_raw_get (const stmdev_ctx_t * ctx, int16_t * val)
Temperature data output register (r).
L and H registers together express a 16-bit word in two’s complement.[get]
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1276 of file lsm9ds1_reg.c.
References LSM9DS1_OUT_TEMP_L, and lsm9ds1_read_reg().