ICARUS OS: LSM9DS1_Common
LSM9DS1_Common
LSM9DS1
Functions
int32_t lsm9ds1_dev_id_get (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, lsm9ds1_id_t *buff)
DeviceWhoamI.
int32_t lsm9ds1_dev_status_get (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, lsm9ds1_status_t *val)
Device status register.
int32_t lsm9ds1_dev_reset_set (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, uint8_t val)
Software reset.
int32_t lsm9ds1_dev_reset_get (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, uint8_t *val)
Software reset.
int32_t lsm9ds1_dev_data_format_set (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, lsm9ds1_ble_t val)
Big/Little Endian data selection.
int32_t lsm9ds1_dev_data_format_get (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, lsm9ds1_ble_t *val)
Big/Little Endian data selection.
int32_t lsm9ds1_dev_boot_set (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, uint8_t val)
Reboot memory content.
int32_t lsm9ds1_dev_boot_get (const stmdev_ctx_t *ctx_mag, stmdev_ctx_t *ctx_imu, uint8_t *val)
Reboot memory content.
Detailed Description
This section groups common useful functions.
Function Documentation
lsm9ds1_dev_boot_get()
int32_t lsm9ds1_dev_boot_get (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, uint8_t * val)
Reboot memory content.
Reload the calibration parameters.[get]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Get the values of boot in reg CTRL_REG8.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1660 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg8_t::boot, LSM9DS1_CTRL_REG2_M, LSM9DS1_CTRL_REG8, and lsm9ds1_read_reg().
lsm9ds1_dev_boot_set()
int32_t lsm9ds1_dev_boot_set (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, uint8_t val)
Reboot memory content.
Reload the calibration parameters.[set]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Change the values of boot in reg CTRL_REG8.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1617 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg8_t::boot, LSM9DS1_CTRL_REG2_M, LSM9DS1_CTRL_REG8, lsm9ds1_read_reg(), lsm9ds1_write_reg(), and lsm9ds1_ctrl_reg2_m_t::reboot.
lsm9ds1_dev_data_format_get()
int32_t lsm9ds1_dev_data_format_get (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, lsm9ds1_ble_t * val)
Big/Little Endian data selection.
[get]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Get the values of ble in reg CTRL_REG8.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1573 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg4_m_t::ble, lsm9ds1_ctrl_reg8_t::ble, LSM9DS1_CTRL_REG4_M, LSM9DS1_CTRL_REG8, LSM9DS1_LSB_LOW_ADDRESS, LSM9DS1_MSB_LOW_ADDRESS, and lsm9ds1_read_reg().
lsm9ds1_dev_data_format_set()
int32_t lsm9ds1_dev_data_format_set (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, lsm9ds1_ble_t val)
Big/Little Endian data selection.
[set]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Change the values of "ble" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1530 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg4_m_t::ble, lsm9ds1_ctrl_reg8_t::ble, LSM9DS1_CTRL_REG4_M, LSM9DS1_CTRL_REG8, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_dev_id_get()
int32_t lsm9ds1_dev_id_get (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, lsm9ds1_id_t * buff)
DeviceWhoamI.
[get]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1403 of file lsm9ds1_reg.c.
References lsm9ds1_id_t::imu, lsm9ds1_read_reg(), LSM9DS1_WHO_AM_I, LSM9DS1_WHO_AM_I_M, and lsm9ds1_id_t::mag.
lsm9ds1_dev_reset_get()
int32_t lsm9ds1_dev_reset_get (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, uint8_t * val)
Software reset.
Restore the default values in user registers.[get]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Get the values of sw_reset in reg CTRL_REG8.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1500 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG2_M, LSM9DS1_CTRL_REG8, lsm9ds1_read_reg(), and lsm9ds1_ctrl_reg8_t::sw_reset.
lsm9ds1_dev_reset_set()
int32_t lsm9ds1_dev_reset_set (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, uint8_t val)
Software reset.
Restore the default values in user registers.[set]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Change the values of sw_reset in reg CTRL_REG8.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1457 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG2_M, LSM9DS1_CTRL_REG8, lsm9ds1_read_reg(), lsm9ds1_write_reg(), lsm9ds1_ctrl_reg2_m_t::soft_rst, and lsm9ds1_ctrl_reg8_t::sw_reset.
lsm9ds1_dev_status_get()
int32_t lsm9ds1_dev_status_get (const stmdev_ctx_t * ctx_mag, stmdev_ctx_t * ctx_imu, lsm9ds1_status_t * val)
Device status register.
[get]
Parameters
ctx_mag Read / write magnetometer interface definitions.(ptr)
ctx_imu Read / write imu interface definitions.(ptr)
val Device status registers.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 1430 of file lsm9ds1_reg.c.
References lsm9ds1_read_reg(), LSM9DS1_STATUS_REG, LSM9DS1_STATUS_REG_M, lsm9ds1_status_t::status_imu, and lsm9ds1_status_t::status_mag.