ICARUS OS: LSM9DS1_Fifo
LSM9DS1_Fifo
LSM9DS1
Functions
int32_t lsm9ds1_fifo_stop_on_wtm_set (const stmdev_ctx_t *ctx, uint8_t val)
Sensing chain FIFO stop values memorization at threshold level.
int32_t lsm9ds1_fifo_stop_on_wtm_get (const stmdev_ctx_t *ctx, uint8_t *val)
Sensing chain FIFO stop values memorization at threshold level.
int32_t lsm9ds1_fifo_mode_set (const stmdev_ctx_t *ctx, lsm9ds1_fifo_md_t val)
FIFO mode selection.
int32_t lsm9ds1_fifo_mode_get (const stmdev_ctx_t *ctx, lsm9ds1_fifo_md_t *val)
FIFO mode selection.
int32_t lsm9ds1_fifo_temp_batch_set (const stmdev_ctx_t *ctx, uint8_t val)
Batching of temperature data.
int32_t lsm9ds1_fifo_temp_batch_get (const stmdev_ctx_t *ctx, uint8_t *val)
Batching of temperature data.
int32_t lsm9ds1_fifo_watermark_set (const stmdev_ctx_t *ctx, uint8_t val)
FIFO watermark level selection.
int32_t lsm9ds1_fifo_watermark_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFO watermark level selection.
int32_t lsm9ds1_fifo_full_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFOfullstatus.
int32_t lsm9ds1_fifo_data_level_get (const stmdev_ctx_t *ctx, uint8_t *val)
Number of unread words (16-bit axes) stored in FIFO.
int32_t lsm9ds1_fifo_ovr_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFO overrun status.
int32_t lsm9ds1_fifo_wtm_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFO watermark status.
Detailed Description
This section group all the functions concerning the fifo usage
Function Documentation
lsm9ds1_fifo_data_level_get()
int32_t lsm9ds1_fifo_data_level_get (const stmdev_ctx_t * ctx, uint8_t * val)
Number of unread words (16-bit axes) stored in FIFO.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Iet the values of "fss" in reg FIFO_SRC.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4558 of file lsm9ds1_reg.c.
References lsm9ds1_fifo_src_t::fss, LSM9DS1_FIFO_SRC, and lsm9ds1_read_reg().
lsm9ds1_fifo_full_flag_get()
int32_t lsm9ds1_fifo_full_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFOfullstatus.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Iet the values of "fss" in reg FIFO_SRC.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4539 of file lsm9ds1_reg.c.
References lsm9ds1_fifo_src_t::fss, LSM9DS1_FIFO_SRC, and lsm9ds1_read_reg().
lsm9ds1_fifo_mode_get()
int32_t lsm9ds1_fifo_mode_get (const stmdev_ctx_t * ctx, lsm9ds1_fifo_md_t * val)
FIFO mode selection.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fifo_en in reg CTRL_REG9.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4397 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg9_t::fifo_en, LSM9DS1_BYPASS_MODE, LSM9DS1_BYPASS_TO_STREAM_MODE, LSM9DS1_CTRL_REG9, LSM9DS1_FIFO_CTRL, LSM9DS1_FIFO_MODE, LSM9DS1_FIFO_OFF, lsm9ds1_read_reg(), LSM9DS1_STREAM_MODE, and LSM9DS1_STREAM_TO_FIFO_MODE.
lsm9ds1_fifo_mode_set()
int32_t lsm9ds1_fifo_mode_set (const stmdev_ctx_t * ctx, lsm9ds1_fifo_md_t val)
FIFO mode selection.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "fifo_en" in reg LSM9DS1.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4360 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg9_t::fifo_en, lsm9ds1_fifo_ctrl_t::fmode, LSM9DS1_CTRL_REG9, LSM9DS1_FIFO_CTRL, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_fifo_ovr_flag_get()
int32_t lsm9ds1_fifo_ovr_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFO overrun status.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Iet the values of "ovrn" in reg FIFO_SRC.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4577 of file lsm9ds1_reg.c.
References LSM9DS1_FIFO_SRC, lsm9ds1_read_reg(), and lsm9ds1_fifo_src_t::ovrn.
lsm9ds1_fifo_stop_on_wtm_get()
int32_t lsm9ds1_fifo_stop_on_wtm_get (const stmdev_ctx_t * ctx, uint8_t * val)
Sensing chain FIFO stop values memorization at threshold level.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of stop_on_fth in reg CTRL_REG9.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4341 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG9, lsm9ds1_read_reg(), and lsm9ds1_ctrl_reg9_t::stop_on_fth.
lsm9ds1_fifo_stop_on_wtm_set()
int32_t lsm9ds1_fifo_stop_on_wtm_set (const stmdev_ctx_t * ctx, uint8_t val)
Sensing chain FIFO stop values memorization at threshold level.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of stop_on_fth in reg CTRL_REG9.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4316 of file lsm9ds1_reg.c.
References LSM9DS1_CTRL_REG9, lsm9ds1_read_reg(), lsm9ds1_write_reg(), and lsm9ds1_ctrl_reg9_t::stop_on_fth.
lsm9ds1_fifo_temp_batch_get()
int32_t lsm9ds1_fifo_temp_batch_get (const stmdev_ctx_t * ctx, uint8_t * val)
Batching of temperature data.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fifo_temp_en in reg CTRL_REG9.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4477 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg9_t::fifo_temp_en, LSM9DS1_CTRL_REG9, and lsm9ds1_read_reg().
lsm9ds1_fifo_temp_batch_set()
int32_t lsm9ds1_fifo_temp_batch_set (const stmdev_ctx_t * ctx, uint8_t val)
Batching of temperature data.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of fifo_temp_en in reg CTRL_REG9.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4453 of file lsm9ds1_reg.c.
References lsm9ds1_ctrl_reg9_t::fifo_temp_en, LSM9DS1_CTRL_REG9, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_fifo_watermark_get()
int32_t lsm9ds1_fifo_watermark_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFO watermark level selection.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fth in reg FIFO_CTRL.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4520 of file lsm9ds1_reg.c.
References lsm9ds1_fifo_ctrl_t::fth, LSM9DS1_FIFO_CTRL, and lsm9ds1_read_reg().
lsm9ds1_fifo_watermark_set()
int32_t lsm9ds1_fifo_watermark_set (const stmdev_ctx_t * ctx, uint8_t val)
FIFO watermark level selection.
[set]
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of fth in reg FIFO_CTRL.
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4496 of file lsm9ds1_reg.c.
References lsm9ds1_fifo_ctrl_t::fth, LSM9DS1_FIFO_CTRL, lsm9ds1_read_reg(), and lsm9ds1_write_reg().
lsm9ds1_fifo_wtm_flag_get()
int32_t lsm9ds1_fifo_wtm_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFO watermark status.
[get]
Parameters
ctx Read / write interface definitions.(ptr)
val Iet the values of "fth" in reg FIFO_SRC.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error).
Definition at line 4596 of file lsm9ds1_reg.c.
References lsm9ds1_fifo_src_t::fth, LSM9DS1_FIFO_SRC, and lsm9ds1_read_reg().