ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Inc/icarus/icarus_task.h File Reference
icarus_task.h File Reference
ICARUS OS Task Management API.
#include <stdint.h>
#include <stdbool.h>
#include "icarus_config.h"
#include "icarus_types.h"
Functions
void os_init (void)
Initialize the ICARUS kernel.
void os_start (void)
Start the ICARUS scheduler.
void os_register_task (void(*function)(void), const char *name)
Register a task with automatic stack allocation.
void os_create_task (icarus_task_t *task, void(*function)(void), uint32_t *stack, uint32_t stack_size, const char *name)
Create a task with explicit stack allocation.
void os_yield (void)
Voluntarily yield CPU to scheduler.
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified number of ticks (non-blocking)
uint32_t task_blocking_sleep (uint32_t ticks)
Sleep with interrupts disabled (blocking)
uint32_t task_busy_wait (uint32_t ticks)
Busy-wait for specified ticks (must be in critical section)
void os_exit_task (void)
Terminate current task normally.
void os_kill_process (uint8_t task_index)
Terminate another task.
void os_task_suicide (void)
Terminate current task (suicide)
uint32_t os_get_tick_count (void)
Get current system tick count.
uint8_t os_get_running_task_count (void)
Get number of active tasks.
const char * os_get_current_task_name (void)
Get name of currently executing task.
uint32_t os_get_task_ticks_remaining (void)
Get remaining ticks in current time slice.
bool semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Initialize a counting semaphore.
bool semaphore_feed (uint8_t semaphore_idx)
Increment semaphore count (V operation / signal)
bool semaphore_consume (uint8_t semaphore_idx)
Decrement semaphore count (P operation / wait)
uint32_t semaphore_get_count (uint8_t semaphore_idx)
Get current semaphore count.
uint32_t semaphore_get_max_count (uint8_t semaphore_idx)
Get semaphore maximum count.
bool pipe_init (uint8_t pipe_idx, uint8_t pipe_capacity_bytes)
Initialize a message pipe.
bool pipe_enqueue (uint8_t pipe_idx, uint8_t *message, uint8_t message_bytes)
Enqueue message to pipe.
bool pipe_dequeue (uint8_t pipe_idx, uint8_t *message, uint8_t message_bytes)
Dequeue message from pipe.
uint8_t pipe_get_count (uint8_t pipe_idx)
Get current byte count in pipe.
uint8_t pipe_get_max_count (uint8_t pipe_idx)
Get pipe capacity.
Detailed Description
ICARUS OS Task Management API.
Version
0.1.0
Public API for task creation, scheduling, and lifecycle management. This is the primary interface for application code to interact with the ICARUS kernel.
Example Usage:
// Register a task with the kernel
os_register_task(my_task_function, "MyTask");
// Start the scheduler
os_start();
// Inside a task: yield CPU voluntarily
os_yield();
// Inside a task: sleep for 100 ticks
task_active_sleep(100);
See also
docs/do178c/design/SDD.md Section 5 - Task Management
docs/do178c/requirements/SRS.md Section 3.1 - Task Requirements
Author
Souham Biswas
Date
2025
Copyright
Copyright 2025 Souham Biswas https://github.com/ironhide23586/icarus-os-core Licensed under the Apache License, Version 2.0
Definition in file icarus_task.h.
Function Documentation
os_create_task()
void os_create_task (icarus_task_t * task, void(* function)(void), uint32_t * stack, uint32_t stack_size, const char * name)
Create a task with explicit stack allocation.
Advanced task creation with user-provided stack. Use this when you need control over stack placement or size.
Parameters
[out] task Pointer to task control block to initialize
[in] function Task entry point function
[in] stack Pointer to stack memory (must be 8-byte aligned)
[in] stack_size Stack size in 32-bit words
[in] name Human-readable task name
Precondition
task != NULL
function != NULL
stack != NULL and 8-byte aligned
stack_size >= 64 (minimum viable stack)
Create a task with explicit stack allocation.
Initializes a task control block (TCB) with the provided parameters and prepares the stack for first execution. The task is created in COLD state and will begin execution when the scheduler runs.
The stack is initialized with an ARM Cortex-M exception frame so that the first context switch properly loads the task's entry point and initial register values.
Stack Frame Layout (ARM Cortex-M):
Offset Register Value
SP+28 xPSR 0x01000000 (Thumb bit)
SP+24 PC function entry point
SP+20 LR os_exit_task (return)
SP+16 R12 0
SP+12 R3 0
SP+8 R2 0
SP+4 R1 0
SP+0 R0 0 <- Initial SP
Parameters
task Pointer to TCB to initialize
function Task entry point function
stack Pointer to stack memory (must be word-aligned)
stack_size Stack size in 32-bit words
name Task name (max ICARUS_MAX_TASK_NAME_LEN chars)
Precondition
task pointer must be valid
function must be a valid function pointer
stack must be word-aligned and have stack_size words
running_task_count < ICARUS_MAX_TASKS
Postcondition
TCB is fully initialized
Stack frame is prepared for first context switch
num_created_tasks is incremented
Task is in TASK_STATE_COLD state
Note
Use os_register_task() for simpler task creation with auto stack
Task name is truncated if longer than ICARUS_MAX_TASK_NAME_LEN
See also
os_register_task() for simplified task creation
ICARUS_STACK_WORDS for default stack size
Example:
static uint32_t my_stack[256];
icarus_task_t my_tcb;
os_create_task(&my_tcb, my_task_func, my_stack, 256, "MyTask");
Definition at line 1072 of file icarus_task.c.
References icarus_task_t::function, icarus_task_t::global_tick_paused, ICARUS_MAX_TASK_NAME_LEN, ICARUS_MAX_TASKS, icarus_task_t::name, num_created_tasks, os_exit_task(), running_task_count, icarus_task_t::stack_base, icarus_task_t::stack_pointer, icarus_task_t::stack_size, icarus_task_t::task_priority, TASK_PRIORITY_LOW, icarus_task_t::task_state, TASK_STATE_COLD, and icarus_task_t::ticks_to_pause.
Referenced by os_register_task().
os_exit_task()
void os_exit_task (void)
Terminate current task normally.
Marks the current task as FINISHED and yields to scheduler. The task's resources are queued for cleanup.
Note
This is automatically called if a task function returns.
Warning
Do not call from interrupt context!
Terminate current task normally.
Marks the current task as FINISHED and removes it from the active task pool. The task's resources are queued for cleanup and the scheduler immediately switches to the next ready task.
This function is automatically called if a task function returns (set as LR during task creation). Tasks can also call it explicitly to terminate early.
Precondition
Called from task context (not ISR)
Scheduler must be running
Postcondition
Task state set to TASK_STATE_FINISHED
running_task_count decremented
Task index added to cleanup queue
Context switch to next task occurs
Note
Task resources (stack, TCB) remain allocated until reused
System tasks (idle, heartbeat) should never call this
Warning
This function does not return to the calling task!
See also
os_kill_process() to terminate another task
os_task_suicide() for explicit self-termination with logging
Example:
void one_shot_task(void) {
    do_initialization();
    os_exit_task();  // Task complete, exit gracefully
    // Unreachable
}
Definition at line 888 of file icarus_task.c.
References cleanup_task_idx, current_cleanup_task_idx, current_task_index, ICARUS_MAX_TASKS, os_yield(), running_task_count, task_list, icarus_task_t::task_state, and TASK_STATE_FINISHED.
Referenced by os_create_task().
os_get_current_task_name()
const char * os_get_current_task_name (void)
Get name of currently executing task.
Returns
Pointer to task name string, or "unknown" if invalid
Get name of currently executing task.
Returns a pointer to the null-terminated name string of the task currently running on the CPU. The name is set during task creation via os_register_task() or os_create_task().
Returns
const char* Pointer to task name string, or "unknown" if no valid task is running
Note
The returned pointer is valid for the lifetime of the task
Maximum name length is ICARUS_MAX_TASK_NAME_LEN (32 chars)
See also
os_register_task()
ICARUS_MAX_TASK_NAME_LEN
Example:
printf("Running: %s\n", os_get_current_task_name());
Definition at line 566 of file icarus_task.c.
References current_task_index, icarus_task_t::name, num_created_tasks, and task_list.
Referenced by os_heartbeat_task().
os_get_running_task_count()
uint8_t os_get_running_task_count (void)
Get number of active tasks.
Returns
Count of tasks in RUNNING, READY, or BLOCKED state
Get number of active tasks.
Returns the number of tasks currently in RUNNING, READY, or BLOCKED states. Does not include KILLED or FINISHED tasks.
This count is used by the scheduler to determine if there are tasks available to run.
Returns
uint8_t Number of active tasks (0 to ICARUS_MAX_TASKS)
Note
Includes system tasks (idle, heartbeat) in the count
See also
os_register_task()
os_kill_process()
Definition at line 540 of file icarus_task.c.
References running_task_count.
os_get_task_ticks_remaining()
uint32_t os_get_task_ticks_remaining (void)
Get remaining ticks in current time slice.
Returns
Ticks remaining before preemption
Get remaining ticks in current time slice.
Returns the number of ticks remaining before the scheduler will preempt the current task. This value is decremented by SysTick_Handler and reset to ticks_per_task on context switch or explicit yield.
Returns
uint32_t Ticks remaining (0 to ICARUS_TICKS_PER_TASK)
Note
A value of 0 indicates preemption is imminent
Useful for tasks that need to complete atomic operations before being preempted
See also
ICARUS_TICKS_PER_TASK
os_yield()
Example:
if (os_get_task_ticks_remaining() < 5) {
    os_yield();  // Voluntarily yield before preemption
}
Definition at line 599 of file icarus_task.c.
References current_task_ticks_remaining.
os_get_tick_count()
uint32_t os_get_tick_count (void)
Get current system tick count.
Returns
Number of SysTick interrupts since os_start()
Note
This function is placed in ITCM for zero wait-state execution.
Tick count wraps at UINT32_MAX (~49 days at 1ms tick)
Get current system tick count.
Returns the number of SysTick interrupts since os_start() was called. The tick count is incremented by SysTick_Handler at the rate configured by ICARUS_TICK_RATE_HZ (default 1000 Hz).
This function is placed in ITCM for zero wait-state access as it is called frequently by timing-sensitive code.
Returns
uint32_t Current tick count (wraps at 2^32)
Note
Tick count wraps approximately every 49.7 days at 1kHz
Thread-safe: reads volatile variable atomically
Timing Calculations:
Ticks to milliseconds: ticks * 1000 / ICARUS_TICK_RATE_HZ
Milliseconds to ticks: ms * ICARUS_TICK_RATE_HZ / 1000
See also
ICARUS_TICK_RATE_HZ
SysTick_Handler()
Example:
uint32_t start = os_get_tick_count();
do_work();
uint32_t elapsed = os_get_tick_count() - start;
printf("Work took %lu ticks\n", elapsed);
Definition at line 519 of file icarus_task.c.
References os_tick_count.
os_init()
void os_init (void)
Initialize the ICARUS kernel.
Must be called before any other kernel function. Initializes:
Task pool and task list
Semaphore pool
Message pipe pool
System tasks (idle, heartbeat)
Precondition
HAL must be initialized (hal_init() called)
Postcondition
Kernel is ready for task registration
Note
This function registers two system tasks:
ICARUS_KEEPALIVE_TASK (idle task)
ICARUS_HEARTBEAT_TASK (LED heartbeat)
Initialize the ICARUS kernel.
This function performs complete kernel initialization including:
Resetting all scheduler state variables
Initializing the task pool with empty TCBs
Initializing the semaphore pool
Initializing the message pipe pool
Clearing virtual CPU registers
Registering system tasks (idle and heartbeat)
Memory Initialization:
Pool Count Location
Task TCBs ICARUS_MAX_TASKS DTCM
Semaphores ICARUS_MAX_SEMAPHORES DTCM
Message Pipes ICARUS_MAX_MESSAGE_QUEUES DTCM
Task Stacks ICARUS_MAX_TASKS RAM_D1
Precondition
Hardware must be initialized (clocks, MPU, caches)
hal_init() must have been called
Postcondition
Kernel is ready for task registration via os_register_task()
System tasks (idle, heartbeat) are registered
Scheduler is enabled but not yet running
Note
Call os_start() after registering application tasks to begin multitasking
Warning
Must be called exactly once before any other kernel functions
See also
os_start()
os_register_task()
hal_init()
Example:
int main(void) {
    hal_init();
    os_init();
    os_register_task(my_task, "MyTask");
    os_start();  // Never returns
}
Definition at line 443 of file icarus_task.c.
References __init_pipe(), __init_sem(), cleanup_task_idx, cpu_vregisters, current_cleanup_task_idx, current_task_index, current_task_ticks_remaining, ICARUS_MAX_MESSAGE_QUEUES, ICARUS_MAX_SEMAPHORES, ICARUS_MAX_TASKS, ICARUS_TICKS_PER_TASK, message_pipe_list, message_pipe_pool, os_heartbeat_task(), os_idle_task(), os_register_task(), os_running, running_task_count, scheduler_enabled, semaphore_list, semaphore_pool, task_list, task_pool, and ticks_per_task.
Referenced by main().
os_kill_process()
void os_kill_process (uint8_t task_index)
Terminate another task.
Forcibly terminates the specified task. The task is marked as KILLED and will not be scheduled again.
Parameters
[in] task_index Index of task to kill (0 to num_created_tasks-1)
Note
Cannot kill system tasks (index 0 and 1)
If killing the current task, this triggers a context switch
Terminate another task.
Forcibly terminates the specified task, marking it as KILLED and removing it from the scheduler's active pool. If the killed task is the current task, an immediate context switch occurs.
System tasks (index 0 = idle, index 1 = heartbeat) cannot be killed for system stability.
Parameters
task_index Index of task to kill (0 to num_created_tasks-1)
Precondition
task_index must be valid (< num_created_tasks)
Target task must be in active state (< TASK_STATE_KILLED)
Cannot kill system tasks (index 0 or 1)
Postcondition
Target task state set to TASK_STATE_KILLED
running_task_count decremented
Task index added to cleanup queue
If killing self, context switch occurs
Note
Logs kill action to console via printf
Safe to call on already-killed tasks (no-op)
Warning
Killing a task holding resources may cause deadlocks
No cleanup callbacks are invoked
See also
os_task_suicide() for self-termination
os_exit_task() for graceful exit
Example:
// Watchdog task kills unresponsive tasks
if (task_is_hung(task_idx)) {
    os_kill_process(task_idx);
}
Definition at line 942 of file icarus_task.c.
References cleanup_task_idx, current_cleanup_task_idx, current_task_index, ICARUS_MAX_TASKS, num_created_tasks, os_yield(), running_task_count, task_list, icarus_task_t::task_state, and TASK_STATE_KILLED.
Referenced by os_task_suicide().
os_register_task()
void os_register_task (void(* function)(void), const char * name)
Register a task with automatic stack allocation.
Simplified task registration using the kernel's internal stack pool. This is the recommended method for most applications.
Parameters
[in] function Task entry point (must not return, use os_exit_task())
[in] name Human-readable task name (max ICARUS_MAX_TASK_NAME_LEN-1 chars)
Precondition
os_init() must have been called
num_created_tasks < ICARUS_MAX_TASKS
Example:
void my_task(void) {
    while (1) {
        // Task work here
        task_active_sleep(100);
    }
}
os_register_task(my_task, "MyTask");
Register a task with automatic stack allocation.
Simplified task creation that allocates a TCB and stack from the kernel's static pools. This is the preferred method for creating application tasks.
The task is assigned:
TCB from task_pool[num_created_tasks]
Stack from stack_pool[num_created_tasks]
Stack size of ICARUS_STACK_WORDS (default 512 words = 2KB)
Parameters
function Task entry point function (void (*)(void))
name Task name string (max ICARUS_MAX_TASK_NAME_LEN chars)
Precondition
os_init() must have been called
num_created_tasks < ICARUS_MAX_TASKS
Postcondition
Task is registered and ready to run
num_created_tasks is incremented
Note
Task begins execution when os_start() is called
Tasks are scheduled in registration order initially
Warning
Maximum ICARUS_MAX_TASKS tasks can be registered
See also
os_create_task() for custom stack allocation
ICARUS_MAX_TASKS
ICARUS_STACK_WORDS
Example:
void sensor_task(void) {
    while (1) {
        read_sensors();
        task_active_sleep(100);
    }
}
int main(void) {
    hal_init();
    os_init();
    os_register_task(sensor_task, "SensorTask");
    os_start();
}
Definition at line 1162 of file icarus_task.c.
References ICARUS_STACK_WORDS, num_created_tasks, os_create_task(), stack_pool, and task_list.
Referenced by os_init().
os_start()
void os_start (void)
Start the ICARUS scheduler.
Begins task execution. This function does not return under normal operation. The first registered task will begin execution.
Precondition
os_init() must have been called
At least one task must be registered
Warning
This function enables interrupts and never returns!
Start the ICARUS scheduler.
Begins execution of the first registered task (typically the idle task). This function does not return under normal operation as control is transferred to the task scheduler.
The scheduler uses round-robin preemptive scheduling with configurable time slices (ICARUS_TICKS_PER_TASK).
Precondition
os_init() must have been called
At least one task must be registered
SysTick must be configured for kernel tick rate
Postcondition
First task begins execution
os_running flag is set by first task
Function does not return
Warning
This function never returns!
Must not be called from interrupt context
See also
os_init()
os_register_task()
Example:
int main(void) {
    hal_init();
    os_init();
    os_register_task(app_task, "AppTask");
    os_start();  // Never returns
    // Unreachable code
}
Definition at line 844 of file icarus_task.c.
References current_task_index, ICARUS_MAX_TASKS, num_created_tasks, task_list, and task_start().
Referenced by main().
os_task_suicide()
void os_task_suicide (void)
Terminate current task (suicide)
Convenience function to kill the currently running task. Equivalent to os_kill_process(current_task_index).
Terminate current task (suicide)
Convenience function for a task to terminate itself with diagnostic logging. Equivalent to os_kill_process(current_task_index) but includes a log message indicating voluntary termination.
Precondition
Called from task context (not ISR)
Scheduler must be running
Postcondition
Current task state set to TASK_STATE_KILLED
Log message printed to console
Context switch to next task occurs
Note
Logs "committed suicide" message for debugging
Warning
This function does not return!
System tasks should never call this
See also
os_exit_task() for graceful exit without "suicide" log
os_kill_process() to kill other tasks
Example:
void self_destructing_task(void) {
    if (fatal_error_detected()) {
        os_task_suicide();  // Logs and terminates
    }
}
Definition at line 1007 of file icarus_task.c.
References current_task_index, os_kill_process(), and task_list.
os_yield()
void os_yield (void)
Voluntarily yield CPU to scheduler.
Triggers a context switch to the next ready task. The current task is placed in READY state and will be scheduled again.
Note
This function is placed in ITCM for zero wait-state execution.
Implementation:
Sets PendSV pending bit to trigger context switch at lowest interrupt priority, ensuring clean stack state.
See also
ARMv7-M Architecture Reference Manual, Section B1.5.14 (PendSV)
Causes the current task to immediately give up its remaining time slice and trigger a context switch. The scheduler will select the next ready task using round-robin scheduling.
This function triggers PendSV exception which performs the actual context switch in a safe manner (lowest priority).
Placed in ITCM for zero wait-state execution as this is called frequently by cooperative multitasking code.
Precondition
Scheduler must be running (os_start() called)
Called from task context (not ISR)
Postcondition
Current task is placed at end of ready queue
Next ready task begins execution
Note
Safe to call from any task at any time
Does not block - returns immediately after context switch back
See also
task_active_sleep() for timed yields
os_yield_pendsv() (assembly handler)
Example:
while (work_pending()) {
    do_some_work();
    os_yield();  // Let other tasks run
}
Definition at line 661 of file icarus_task.c.
References current_task_ticks_remaining, and ticks_per_task.
Referenced by os_exit_task(), os_idle_task(), os_kill_process(), and task_active_sleep().
pipe_dequeue()
bool pipe_dequeue (uint8_t pipe_idx, uint8_t * message, uint8_t message_bytes)
Dequeue message from pipe.
Blocks if insufficient data until message is available.
Parameters
[in] pipe_idx Pipe index
[out] message Buffer to receive message data
[in] message_bytes Number of bytes to dequeue
Return values
true Message dequeued successfully
false Invalid parameters or pipe not initialized
Note
This function is placed in ITCM for zero wait-state execution.
Dequeue message from pipe.
Copies the specified number of bytes from the pipe's circular buffer into the provided buffer. If insufficient data is available, the calling task blocks until data arrives.
Bytes are read atomically - either all requested bytes are read or the operation blocks. Partial reads do not occur.
Placed in ITCM for zero wait-state execution.
Parameters
pipe_idx Index of pipe to read from
message Buffer to receive bytes (must be >= message_bytes)
message_bytes Number of bytes to read
Returns
bool true if read succeeded, false if invalid parameters
Return values
true All bytes read successfully
false Invalid pipe, not engaged, or request too large
Precondition
Pipe must be initialized via pipe_init()
pipe_idx < ICARUS_MAX_MESSAGE_QUEUES
message_bytes <= pipe capacity
message buffer must have space for message_bytes
Postcondition
Bytes copied from circular buffer to message
Pipe count decreased by message_bytes
tick_updated_at set to current tick
Note
Blocks if insufficient data available
Thread-safe: uses critical section for buffer update
See also
pipe_enqueue() for writing bytes
pipe_init()
Example:
// Consumer task
void display_task(void) {
    uint8_t reading[4];
    while (1) {
        pipe_dequeue(PIPE_SENSOR, reading, sizeof(reading));
        display_value(reading);
    }
}
Definition at line 1627 of file icarus_task.c.
References icarus_pipe_t::buffer, icarus_pipe_t::count, icarus_pipe_t::dequeue_idx, enter_critical(), exit_critical(), ICARUS_MAX_MESSAGE_QUEUES, icarus_pipe_t::max_count, message_pipe_list, os_tick_count, scheduler_enabled, task_active_sleep(), and icarus_pipe_t::tick_updated_at.
pipe_enqueue()
bool pipe_enqueue (uint8_t pipe_idx, uint8_t * message, uint8_t message_bytes)
Enqueue message to pipe.
Blocks if insufficient space until room is available.
Parameters
[in] pipe_idx Pipe index
[in] message Pointer to message data
[in] message_bytes Number of bytes to enqueue
Return values
true Message enqueued successfully
false Invalid parameters or pipe not initialized
Note
This function is placed in ITCM for zero wait-state execution.
Enqueue message to pipe.
Copies the specified bytes into the pipe's circular buffer. If insufficient space is available, the calling task blocks until space becomes available (via pipe_dequeue()).
Bytes are written atomically - either all bytes are written or the operation blocks. Partial writes do not occur.
Placed in ITCM for zero wait-state execution.
Parameters
pipe_idx Index of pipe to write to
message Pointer to bytes to write
message_bytes Number of bytes to write
Returns
bool true if write succeeded, false if invalid parameters
Return values
true All bytes written successfully
false Invalid pipe, not engaged, or message too large
Precondition
Pipe must be initialized via pipe_init()
pipe_idx < ICARUS_MAX_MESSAGE_QUEUES
message_bytes <= pipe capacity
Postcondition
Bytes copied to circular buffer
Pipe count increased by message_bytes
tick_updated_at set to current tick
Note
Blocks if insufficient space available
Thread-safe: uses critical section for buffer update
See also
pipe_dequeue() for reading bytes
pipe_init()
Example:
// Producer task
void sensor_task(void) {
    uint8_t reading[4];
    while (1) {
        read_sensor(reading, sizeof(reading));
        pipe_enqueue(PIPE_SENSOR, reading, sizeof(reading));
        task_active_sleep(100);
    }
}
Definition at line 1542 of file icarus_task.c.
References icarus_pipe_t::buffer, icarus_pipe_t::count, icarus_pipe_t::enqueue_idx, enter_critical(), exit_critical(), ICARUS_MAX_MESSAGE_QUEUES, icarus_pipe_t::max_count, message_pipe_list, os_tick_count, scheduler_enabled, task_active_sleep(), and icarus_pipe_t::tick_updated_at.
pipe_get_count()
uint8_t pipe_get_count (uint8_t pipe_idx)
Get current byte count in pipe.
Parameters
[in] pipe_idx Pipe index
Returns
Current byte count, or 0 if invalid/uninitialized
Returns the number of bytes currently stored in the pipe's circular buffer. Useful for checking data availability without blocking.
Parameters
pipe_idx Index of pipe to query
Returns
uint8_t Current byte count, or 0 if invalid/not engaged
Precondition
Pipe should be initialized for meaningful result
Note
Non-blocking read operation
Value may change immediately after return
See also
pipe_get_max_count()
pipe_init()
Example:
if (pipe_get_count(PIPE_SENSOR) >= sizeof(reading)) {
    pipe_dequeue(PIPE_SENSOR, reading, sizeof(reading));
}
Definition at line 1688 of file icarus_task.c.
References icarus_pipe_t::count, ICARUS_MAX_MESSAGE_QUEUES, and message_pipe_list.
pipe_get_max_count()
uint8_t pipe_get_max_count (uint8_t pipe_idx)
Get pipe capacity.
Parameters
[in] pipe_idx Pipe index
Returns
Maximum capacity in bytes, or 0 if invalid/uninitialized
Get pipe capacity.
Returns the maximum byte capacity of the specified pipe. This is the value set during pipe_init().
Parameters
pipe_idx Index of pipe to query
Returns
uint8_t Maximum capacity in bytes, or 0 if invalid/not engaged
Precondition
Pipe should be initialized for meaningful result
Note
Non-blocking read operation
Capacity is immutable after initialization
See also
pipe_get_count()
pipe_init()
Example:
uint8_t capacity = pipe_get_max_count(PIPE_SENSOR);
uint8_t used = pipe_get_count(PIPE_SENSOR);
printf("Pipe %d%% full\n", (used * 100) / capacity);
Definition at line 1722 of file icarus_task.c.
References ICARUS_MAX_MESSAGE_QUEUES, icarus_pipe_t::max_count, and message_pipe_list.
pipe_init()
bool pipe_init (uint8_t pipe_idx, uint8_t pipe_capacity_bytes)
Initialize a message pipe.
Parameters
[in] pipe_idx Pipe index (0 to ICARUS_MAX_MESSAGE_QUEUES-1)
[in] pipe_capacity_bytes Maximum bytes the pipe can hold
Return values
true Pipe initialized successfully
false Invalid index, capacity=0, or pipe already in use
Initialize a message pipe.
Configures a message pipe from the kernel's static pool with the specified byte capacity. Message pipes provide byte-stream inter-task communication using a circular buffer.
Message pipes are used for:
Variable-length message passing between tasks
Streaming data (sensor readings, log messages)
Command/response protocols
Parameters
pipe_idx Index in pipe pool (0 to ICARUS_MAX_MESSAGE_QUEUES-1)
pipe_capacity_bytes Maximum buffer size in bytes
Returns
bool true if initialization succeeded, false otherwise
Return values
true Pipe initialized successfully
false Invalid index, zero/excessive capacity, or already engaged
Precondition
os_init() must have been called
pipe_idx < ICARUS_MAX_MESSAGE_QUEUES
0 < pipe_capacity_bytes <= ICARUS_MAX_MESSAGE_BYTES
Pipe must not already be engaged
Postcondition
Pipe buffer cleared to zeros
Pipe marked as engaged
Read/write indices reset to 0
Note
Thread-safe: uses critical section internally
Cannot re-initialize an engaged pipe
See also
pipe_enqueue()
pipe_dequeue()
ICARUS_MAX_MESSAGE_QUEUES
ICARUS_MAX_MESSAGE_BYTES
Example:
#define PIPE_SENSOR 0
#define SENSOR_BUFFER_SIZE 64
if (!pipe_init(PIPE_SENSOR, SENSOR_BUFFER_SIZE)) {
    Error_Handler();
}
Definition at line 1475 of file icarus_task.c.
References __init_pipe(), enter_critical(), exit_critical(), ICARUS_MAX_MESSAGE_BYTES, ICARUS_MAX_MESSAGE_QUEUES, and message_pipe_list.
semaphore_consume()
bool semaphore_consume (uint8_t semaphore_idx)
Decrement semaphore count (P operation / wait)
Blocks if count == 0 until semaphore is signaled.
Parameters
[in] semaphore_idx Semaphore index
Return values
true Operation successful
false Invalid index or semaphore not initialized
Note
This function is placed in ITCM for zero wait-state execution.
Decrements the semaphore count by one, consuming a resource. If the semaphore count is zero, the calling task blocks until another task signals the semaphore via semaphore_feed().
This is the "consumer" side of producer-consumer synchronization. Placed in ITCM for zero wait-state execution.
Parameters
semaphore_idx Index of semaphore to wait on
Returns
bool true if operation succeeded, false if invalid semaphore
Return values
true Count decremented successfully
false Invalid index or semaphore not engaged
Precondition
Semaphore must be initialized via semaphore_init()
semaphore_idx < ICARUS_MAX_SEMAPHORES
Postcondition
Semaphore count decremented by 1
tick_updated_at set to current tick
Note
Blocks if count == 0 until semaphore_feed() is called
Thread-safe: uses critical section for decrement
See also
semaphore_feed() for increment operation
semaphore_init()
Example:
// Consumer task
void consumer_task(void) {
    while (1) {
        semaphore_consume(SEM_DATA_READY);  // Wait for data
        data = read_from_buffer();
        process_data(data);
    }
}
Definition at line 1337 of file icarus_task.c.
References icarus_semaphore_t::count, enter_critical(), exit_critical(), ICARUS_MAX_SEMAPHORES, os_tick_count, semaphore_list, task_active_sleep(), and icarus_semaphore_t::tick_updated_at.
semaphore_feed()
bool semaphore_feed (uint8_t semaphore_idx)
Increment semaphore count (V operation / signal)
Blocks if count == max_count until space is available.
Parameters
[in] semaphore_idx Semaphore index
Return values
true Operation successful
false Invalid index or semaphore not initialized
Note
This function is placed in ITCM for zero wait-state execution.
Increments the semaphore count by one, signaling that a resource is available. If the semaphore is at maximum count, the calling task blocks until space is available.
This is the "producer" side of producer-consumer synchronization. Placed in ITCM for zero wait-state execution.
Parameters
semaphore_idx Index of semaphore to signal
Returns
bool true if operation succeeded, false if invalid semaphore
Return values
true Count incremented successfully
false Invalid index or semaphore not engaged
Precondition
Semaphore must be initialized via semaphore_init()
semaphore_idx < ICARUS_MAX_SEMAPHORES
Postcondition
Semaphore count incremented by 1
tick_updated_at set to current tick
Note
Blocks if count == max_count (bounded semaphore)
Thread-safe: uses critical section for increment
See also
semaphore_consume() for decrement operation
semaphore_init()
Example:
// Producer task
void producer_task(void) {
    while (1) {
        data = produce_data();
        write_to_buffer(data);
        semaphore_feed(SEM_DATA_READY);  // Signal consumer
    }
}
Definition at line 1275 of file icarus_task.c.
References icarus_semaphore_t::count, enter_critical(), exit_critical(), ICARUS_MAX_SEMAPHORES, os_tick_count, semaphore_list, task_active_sleep(), and icarus_semaphore_t::tick_updated_at.
semaphore_get_count()
uint32_t semaphore_get_count (uint8_t semaphore_idx)
Get current semaphore count.
Parameters
[in] semaphore_idx Semaphore index
Returns
Current count, or 0 if invalid/uninitialized
Returns the current count value of the specified semaphore. Useful for monitoring resource availability without blocking.
Parameters
semaphore_idx Index of semaphore to query
Returns
uint32_t Current count, or 0 if invalid/not engaged
Precondition
Semaphore should be initialized for meaningful result
Note
Non-blocking read operation
Value may change immediately after return
See also
semaphore_get_max_count()
semaphore_init()
Example:
uint32_t available = semaphore_get_count(SEM_BUFFER);
printf("Buffer slots available: %lu\n", available);
Definition at line 1381 of file icarus_task.c.
References icarus_semaphore_t::count, ICARUS_MAX_SEMAPHORES, and semaphore_list.
semaphore_get_max_count()
uint32_t semaphore_get_max_count (uint8_t semaphore_idx)
Get semaphore maximum count.
Parameters
[in] semaphore_idx Semaphore index
Returns
Maximum count, or 0 if invalid/uninitialized
Get semaphore maximum count.
Returns the maximum count value (capacity) of the specified semaphore. This is the value set during semaphore_init().
Parameters
semaphore_idx Index of semaphore to query
Returns
uint32_t Maximum count, or 0 if invalid/not engaged
Precondition
Semaphore should be initialized for meaningful result
Note
Non-blocking read operation
Max count is immutable after initialization
See also
semaphore_get_count()
semaphore_init()
Example:
uint32_t capacity = semaphore_get_max_count(SEM_BUFFER);
uint32_t used = capacity - semaphore_get_count(SEM_BUFFER);
printf("Buffer %lu%% full\n", (used * 100) / capacity);
Definition at line 1415 of file icarus_task.c.
References ICARUS_MAX_SEMAPHORES, icarus_semaphore_t::max_count, and semaphore_list.
semaphore_init()
bool semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Initialize a counting semaphore.
Parameters
[in] semaphore_idx Semaphore index (0 to ICARUS_MAX_SEMAPHORES-1)
[in] semaphore_count Initial count (also sets max_count)
Return values
true Semaphore initialized successfully
false Invalid index, count=0, or semaphore already in use
Configures a semaphore from the kernel's static pool with the specified initial and maximum count. The semaphore is marked as engaged (active) upon successful initialization.
Counting semaphores are used for:
Resource counting (e.g., buffer slots available)
Producer-consumer synchronization
Rate limiting
Parameters
semaphore_idx Index in semaphore pool (0 to ICARUS_MAX_SEMAPHORES-1)
semaphore_count Initial and maximum count value
Returns
bool true if initialization succeeded, false otherwise
Return values
true Semaphore initialized successfully
false Invalid index, zero count, or already engaged
Precondition
os_init() must have been called
semaphore_idx < ICARUS_MAX_SEMAPHORES
semaphore_count > 0
Semaphore must not already be engaged
Postcondition
Semaphore count set to semaphore_count
Semaphore max_count set to semaphore_count
Semaphore marked as engaged
Note
Thread-safe: uses critical section internally
Cannot re-initialize an engaged semaphore
See also
semaphore_feed()
semaphore_consume()
ICARUS_MAX_SEMAPHORES
Example:
#define SEM_BUFFER 0
#define BUFFER_SLOTS 10
if (!semaphore_init(SEM_BUFFER, BUFFER_SLOTS)) {
    Error_Handler();
}
Definition at line 1218 of file icarus_task.c.
References __init_sem(), enter_critical(), exit_critical(), and semaphore_list.
task_active_sleep()
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified number of ticks (non-blocking)
Blocks the current task for the specified duration while allowing other tasks to run. This is the preferred sleep method.
Parameters
[in] ticks Number of SysTick intervals to sleep
Returns
Actual number of ticks elapsed (may be >= requested due to scheduling)
Note
This function is placed in ITCM for zero wait-state execution.
Example:
// Sleep for approximately 100ms (at 1ms tick rate)
uint32_t actual = task_active_sleep(100);
Sleep for specified number of ticks (non-blocking)
Puts the current task into BLOCKED state for the specified number of ticks. The scheduler will skip this task until the sleep period expires, allowing other tasks to execute.
This is the preferred sleep method for cooperative multitasking as it does not waste CPU cycles. The task is automatically returned to READY state by the scheduler when ticks expire.
Placed in ITCM for zero wait-state execution.
Parameters
ticks Number of ticks to sleep (1 tick = 1ms at 1kHz)
Returns
uint32_t Actual ticks elapsed (may be >= requested due to scheduling latency)
Precondition
Scheduler must be running
Called from task context (not ISR)
Postcondition
Task state temporarily set to TASK_STATE_BLOCKED
Task resumes after at least 'ticks' have elapsed
Note
Minimum sleep is 1 tick; 0 is treated as immediate yield
Actual sleep may be longer due to higher-priority tasks
See also
task_blocking_sleep() for non-preemptible sleep
task_busy_wait() for spin-wait delay
Example:
// Blink LED at 1Hz
while (1) {
    LED_On();
    task_active_sleep(500);  // 500ms on
    LED_Off();
    task_active_sleep(500);  // 500ms off
}
Definition at line 708 of file icarus_task.c.
References current_task_index, icarus_task_t::global_tick_paused, os_tick_count, os_yield(), task_list, icarus_task_t::task_state, TASK_STATE_BLOCKED, and icarus_task_t::ticks_to_pause.
task_blocking_sleep()
uint32_t task_blocking_sleep (uint32_t ticks)
Sleep with interrupts disabled (blocking)
Busy-waits for the specified duration with scheduler disabled. Use sparingly as this blocks all other tasks.
Parameters
[in] ticks Number of SysTick intervals to wait
Returns
Actual number of ticks elapsed
Warning
This function disables the scheduler! Use only when absolutely necessary (e.g., hardware timing requirements).
Sleep with interrupts disabled (blocking)
Performs a blocking delay within a critical section, preventing any context switches during the sleep period. Uses busy-wait internally but protects against preemption.
Use this when you need guaranteed uninterrupted timing, such as hardware initialization sequences or protocol bit-banging.
Parameters
ticks Number of ticks to sleep (1 tick = 1ms at 1kHz)
Returns
uint32_t Actual ticks elapsed
Precondition
Scheduler must be running
Postcondition
No context switches occur during sleep
Critical section depth is preserved
Warning
Blocks ALL other tasks for the duration - use sparingly!
Long sleeps will cause other tasks to miss deadlines
See also
task_active_sleep() for cooperative sleep (preferred)
task_busy_wait() for spin-wait without critical section
Example:
// Hardware reset sequence requiring precise timing
GPIO_WritePin(RESET_PIN, 0);
task_blocking_sleep(10);  // Hold reset for exactly 10ms
GPIO_WritePin(RESET_PIN, 1);
Definition at line 750 of file icarus_task.c.
References enter_critical(), exit_critical(), and task_busy_wait().
Referenced by __io_putchar().
task_busy_wait()
uint32_t task_busy_wait (uint32_t ticks)
Busy-wait for specified ticks (must be in critical section)
Low-level busy-wait loop. Caller must already be in critical section.
Parameters
[in] ticks Number of ticks to wait
Returns
Actual number of ticks elapsed
Precondition
Must be called from within a critical section
Busy-wait for specified ticks (must be in critical section)
Performs a busy-wait loop, polling the tick counter until the specified number of ticks have elapsed. Does NOT yield to other tasks and does NOT disable the scheduler.
The task may still be preempted during this wait, so actual elapsed time may exceed the requested ticks.
Parameters
ticks Number of ticks to wait (1 tick = 1ms at 1kHz)
Returns
uint32_t Actual ticks elapsed (>= requested)
Note
Wastes CPU cycles - prefer task_active_sleep() when possible
In HOST_TEST mode, auto-advances tick count to prevent hang
Warning
High CPU usage - only use for very short delays
May be preempted, extending actual wait time
See also
task_active_sleep() for cooperative sleep (preferred)
task_blocking_sleep() for non-preemptible delay
Example:
// Short delay for hardware settling
task_busy_wait(2);  // Wait ~2ms for voltage to stabilize
Definition at line 787 of file icarus_task.c.
References os_tick_count.
Referenced by task_blocking_sleep().