ICARUS OS: Core/Src/icarus/icarus_task.c File Reference
icarus_task.c File Reference
ICARUS OS Task Management Implementation.
#include "icarus/icarus_task.h"
#include "bsp/bsp_display.h"
#include "bsp/bsp_led.h"
#include "main.h"
#include <string.h>
#include <stdio.h>
#include <stddef.h>
Macros
#define ITCM_FUNC __attribute__((section(".itcm")))
Place function in ITCM for zero wait-state execution.
#define DTCM_DATA __attribute__((section(".dtcm")))
Functions
void start_cold_task (icarus_task_t *task)
Start execution of a cold (never-run) task.
void os_yield_pendsv (void)
Context switch handler (called from PendSV)
static void enter_critical (void)
Enter critical section (disable scheduler)
static void exit_critical (void)
Exit critical section (re-enable scheduler if outermost)
static void __init_sem (uint8_t semaphore_idx, uint32_t semaphore_count, bool should_engage)
Initialize a semaphore structure.
static void __init_pipe (uint8_t message_pipe_idx, uint8_t max_messages, bool should_engage)
Initialize a message pipe structure.
static void os_idle_task (void)
Idle task - runs when no other tasks are ready.
static void os_heartbeat_task (void)
Heartbeat task - blinks LED to indicate OS is alive.
void os_init (void)
Initialize the ICARUS kernel.
uint32_t os_get_tick_count (void)
Get current system tick count.
uint8_t os_get_running_task_count (void)
Get number of active tasks.
const char * os_get_current_task_name (void)
Get name of currently executing task.
uint32_t os_get_task_ticks_remaining (void)
Get remaining ticks in current time slice.
static void task_start (icarus_task_t *task)
Start a cold task (internal)
void os_yield (void)
Voluntarily yield CPU to scheduler.
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified number of ticks (non-blocking)
uint32_t task_blocking_sleep (uint32_t ticks)
Sleep with interrupts disabled (blocking)
uint32_t task_busy_wait (uint32_t ticks)
Busy-wait for specified ticks (must be in critical section)
void os_start (void)
Start the ICARUS scheduler.
void os_exit_task (void)
Terminate current task normally.
void os_kill_process (uint8_t task_index)
Terminate another task.
void os_task_suicide (void)
Terminate current task (suicide)
void os_create_task (icarus_task_t *task, void(*function)(void), uint32_t *stack, uint32_t stack_size, const char *name)
Create a task with explicit stack allocation.
void os_register_task (void(*function)(void), const char *name)
Register a task with automatic stack allocation.
bool semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Initialize a counting semaphore.
bool semaphore_feed (uint8_t semaphore_idx)
Increment semaphore count (V operation / signal)
bool semaphore_consume (uint8_t semaphore_idx)
Decrement semaphore count (P operation / wait)
uint32_t semaphore_get_count (uint8_t semaphore_idx)
Get current semaphore count.
uint32_t semaphore_get_max_count (uint8_t semaphore_idx)
Get semaphore maximum count.
bool pipe_init (uint8_t pipe_idx, uint8_t pipe_capacity_bytes)
Initialize a message pipe.
bool pipe_enqueue (uint8_t pipe_idx, uint8_t *message, uint8_t message_bytes)
Enqueue message to pipe.
bool pipe_dequeue (uint8_t pipe_idx, uint8_t *message, uint8_t message_bytes)
Dequeue message from pipe.
uint8_t pipe_get_count (uint8_t pipe_idx)
Get current byte count in pipe.
uint8_t pipe_get_max_count (uint8_t pipe_idx)
Get pipe capacity.
Variables
icarus_task_t * task_list [128]
Array of pointers to all task control blocks.
icarus_semaphore_t * semaphore_list [64]
Array of pointers to all semaphores.
icarus_pipe_t * message_pipe_list [64]
Array of pointers to all message pipes.
static icarus_task_t task_pool [128]
Static pool of task control blocks.
static icarus_semaphore_t semaphore_pool [64]
Static pool of semaphores.
static icarus_pipe_t message_pipe_pool [64]
Static pool of message pipes.
static int8_t cleanup_task_idx [128]
Queue of task indices pending cleanup.
uint8_t current_task_index
Index of currently executing task.
uint8_t running_task_count
Count of tasks in active states (RUNNING/READY/BLOCKED)
uint8_t num_created_tasks
Total number of created tasks.
volatile uint32_t current_task_ticks_remaining
Ticks remaining in current task's time slice.
volatile uint32_t ticks_per_task
Configured ticks per time slice.
uint32_t cpu_vregisters [16]
Virtual CPU registers for context save/restore.
volatile uint32_t os_tick_count
System tick counter (incremented by SysTick_Handler)
volatile uint8_t os_running
Flag indicating OS is running (tasks are executing)
volatile uint8_t critical_stack_depth
Critical section nesting depth.
volatile bool scheduler_enabled
Scheduler enable flag (false during critical sections)
int8_t current_cleanup_task_idx
Index into cleanup_task_idx array.
static uint32_t stack_pool [128][512]
Static stack pool for all tasks.
Detailed Description
ICARUS OS Task Management Implementation.
Version
0.1.0
Core kernel implementation including:
Task creation and lifecycle management
Round-robin preemptive scheduler
Counting semaphores
Message pipes (queues)
Memory Layout (STM32H750):
DTCM (128KB): Task pools, semaphores, pipes - zero wait-state
ITCM (64KB): Hot-path functions - zero wait-state
RAM_D1 (512KB): Stack pool, BSS
See also
docs/do178c/design/SDD.md for detailed design documentation
STM32H750 Reference Manual RM0433 for memory architecture
Author
Souham Biswas
Date
2026
Copyright
Copyright (c) 2026 ICARUS Project https://github.com/ironhide23586/icarus-os-core Licensed under MIT License
Definition in file icarus_task.c.
Macro Definition Documentation
DTCM_DATA
#define DTCM_DATA __attribute__((section(".dtcm")))
Definition at line 54 of file icarus_task.c.
ITCM_FUNC
#define ITCM_FUNC __attribute__((section(".itcm")))
Place function in ITCM for zero wait-state execution.
Note
ITCM is 64KB, use sparingly for hot-path code only
See also
STM32H750 Reference Manual RM0433, Section 2.3.1
Definition at line 53 of file icarus_task.c.
Function Documentation
__init_pipe()
static void __init_pipe (uint8_t message_pipe_idx, uint8_t max_messages, bool should_engage) inline static
Initialize a message pipe structure.
Parameters
message_pipe_idx Index in pipe pool
max_messages Maximum buffer capacity
should_engage Whether to mark as active
Definition at line 237 of file icarus_task.c.
References icarus_pipe_t::buffer, icarus_pipe_t::count, icarus_pipe_t::dequeue_idx, icarus_pipe_t::engaged, icarus_pipe_t::enqueue_idx, ICARUS_MAX_MESSAGE_BYTES, icarus_pipe_t::max_count, message_pipe_list, os_tick_count, and icarus_pipe_t::tick_updated_at.
Referenced by os_init(), and pipe_init().
__init_sem()
static void __init_sem (uint8_t semaphore_idx, uint32_t semaphore_count, bool should_engage) inline static
Initialize a semaphore structure.
Parameters
semaphore_idx Index in semaphore pool
semaphore_count Initial/max count
should_engage Whether to mark as active
Definition at line 222 of file icarus_task.c.
References icarus_semaphore_t::count, icarus_semaphore_t::engaged, icarus_semaphore_t::max_count, os_tick_count, semaphore_list, and icarus_semaphore_t::tick_updated_at.
Referenced by os_init(), and semaphore_init().
enter_critical()
static void enter_critical (void) inline static
Enter critical section (disable scheduler)
Note
Supports nesting - must pair with exit_critical()
Definition at line 195 of file icarus_task.c.
References critical_stack_depth, and scheduler_enabled.
Referenced by pipe_dequeue(), pipe_enqueue(), pipe_init(), semaphore_consume(), semaphore_feed(), semaphore_init(), and task_blocking_sleep().
exit_critical()
static void exit_critical (void) inline static
Exit critical section (re-enable scheduler if outermost)
Note
Supports nesting - must pair with enter_critical()
Definition at line 205 of file icarus_task.c.
References critical_stack_depth, and scheduler_enabled.
Referenced by pipe_dequeue(), pipe_enqueue(), pipe_init(), semaphore_consume(), semaphore_feed(), semaphore_init(), and task_blocking_sleep().
os_create_task()
void os_create_task (icarus_task_t * task, void(* function)(void), uint32_t * stack, uint32_t stack_size, const char * name)
Create a task with explicit stack allocation.
Advanced task creation with user-provided stack. Use this when you need control over stack placement or size.
Parameters
[out] task Pointer to task control block to initialize
[in] function Task entry point function
[in] stack Pointer to stack memory (must be 8-byte aligned)
[in] stack_size Stack size in 32-bit words
[in] name Human-readable task name
Precondition
task != NULL
function != NULL
stack != NULL and 8-byte aligned
stack_size >= 64 (minimum viable stack)
Definition at line 509 of file icarus_task.c.
References icarus_task_t::function, icarus_task_t::global_tick_paused, ICARUS_MAX_TASK_NAME_LEN, ICARUS_MAX_TASKS, icarus_task_t::name, num_created_tasks, os_exit_task(), running_task_count, icarus_task_t::stack_base, icarus_task_t::stack_pointer, icarus_task_t::stack_size, icarus_task_t::task_priority, TASK_PRIORITY_LOW, icarus_task_t::task_state, TASK_STATE_COLD, and icarus_task_t::ticks_to_pause.
Referenced by os_register_task().
os_exit_task()
void os_exit_task (void)
Terminate current task normally.
Marks the current task as FINISHED and yields to scheduler. The task's resources are queued for cleanup.
Note
This is automatically called if a task function returns.
Warning
Do not call from interrupt context!
Definition at line 449 of file icarus_task.c.
References cleanup_task_idx, current_cleanup_task_idx, current_task_index, ICARUS_MAX_TASKS, os_yield(), running_task_count, task_list, icarus_task_t::task_state, and TASK_STATE_FINISHED.
Referenced by os_create_task().
os_get_current_task_name()
const char * os_get_current_task_name (void)
Get name of currently executing task.
Returns
Pointer to task name string, or "unknown" if invalid
Definition at line 369 of file icarus_task.c.
References current_task_index, icarus_task_t::name, num_created_tasks, and task_list.
Referenced by os_heartbeat_task().
os_get_running_task_count()
uint8_t os_get_running_task_count (void)
Get number of active tasks.
Returns
Count of tasks in RUNNING, READY, or BLOCKED state
Definition at line 364 of file icarus_task.c.
References running_task_count.
os_get_task_ticks_remaining()
uint32_t os_get_task_ticks_remaining (void)
Get remaining ticks in current time slice.
Returns
Ticks remaining before preemption
Definition at line 378 of file icarus_task.c.
References current_task_ticks_remaining.
os_get_tick_count()
uint32_t os_get_tick_count (void)
Get current system tick count.
Returns
Number of SysTick interrupts since os_start()
Note
This function is placed in ITCM for zero wait-state execution.
Tick count wraps at UINT32_MAX (~49 days at 1ms tick)
Definition at line 359 of file icarus_task.c.
References os_tick_count.
os_heartbeat_task()
static void os_heartbeat_task (void) static
Heartbeat task - blinks LED to indicate OS is alive.
Note
Visual confirmation that scheduler is running
< Heartbeat indicator row
< Heartbeat indicator row
< Heartbeat indicator row
Definition at line 276 of file icarus_task.c.
References display_render_banner(), ICARUS_HEARTBEAT_OFF_TICKS, ICARUS_HEARTBEAT_ON_TICKS, LED_Blink(), LED_Off(), LED_On(), os_get_current_task_name(), os_running, ROW_HEARTBEAT, and task_active_sleep().
Referenced by os_init().
os_idle_task()
static void os_idle_task (void) static
Idle task - runs when no other tasks are ready.
Note
Initializes display on first run, then yields continuously
Definition at line 261 of file icarus_task.c.
References display_init(), and os_yield().
Referenced by os_init().
os_init()
void os_init (void)
Initialize the ICARUS kernel.
Must be called before any other kernel function. Initializes:
Task pool and task list
Semaphore pool
Message pipe pool
System tasks (idle, heartbeat)
Precondition
HAL must be initialized (hal_init() called)
Postcondition
Kernel is ready for task registration
Note
This function registers two system tasks:
ICARUS_KEEPALIVE_TASK (idle task)
ICARUS_HEARTBEAT_TASK (LED heartbeat)
Definition at line 313 of file icarus_task.c.
References __init_pipe(), __init_sem(), cleanup_task_idx, cpu_vregisters, current_cleanup_task_idx, current_task_index, current_task_ticks_remaining, ICARUS_MAX_MESSAGE_QUEUES, ICARUS_MAX_SEMAPHORES, ICARUS_MAX_TASKS, ICARUS_TICKS_PER_TASK, message_pipe_list, message_pipe_pool, os_heartbeat_task(), os_idle_task(), os_register_task(), os_running, running_task_count, scheduler_enabled, semaphore_list, semaphore_pool, task_list, task_pool, and ticks_per_task.
Referenced by main().
os_kill_process()
void os_kill_process (uint8_t task_index)
Terminate another task.
Forcibly terminates the specified task. The task is marked as KILLED and will not be scheduled again.
Parameters
[in] task_index Index of task to kill (0 to num_created_tasks-1)
Note
Cannot kill system tasks (index 0 and 1)
If killing the current task, this triggers a context switch
Definition at line 464 of file icarus_task.c.
References cleanup_task_idx, current_cleanup_task_idx, current_task_index, ICARUS_MAX_TASKS, num_created_tasks, os_yield(), running_task_count, task_list, icarus_task_t::task_state, and TASK_STATE_KILLED.
Referenced by os_task_suicide().
os_register_task()
void os_register_task (void(* function)(void), const char * name)
Register a task with automatic stack allocation.
Simplified task registration using the kernel's internal stack pool. This is the recommended method for most applications.
Parameters
[in] function Task entry point (must not return, use os_exit_task())
[in] name Human-readable task name (max ICARUS_MAX_TASK_NAME_LEN-1 chars)
Precondition
os_init() must have been called
num_created_tasks < ICARUS_MAX_TASKS
Example:
void my_task(void) {
    while (1) {
        // Task work here
        task_active_sleep(100);
    }
}
os_register_task(my_task, "MyTask");
Definition at line 552 of file icarus_task.c.
References ICARUS_STACK_WORDS, num_created_tasks, os_create_task(), stack_pool, and task_list.
Referenced by os_init().
os_start()
void os_start (void)
Start the ICARUS scheduler.
Begins task execution. This function does not return under normal operation. The first registered task will begin execution.
Precondition
os_init() must have been called
At least one task must be registered
Warning
This function enables interrupts and never returns!
Definition at line 441 of file icarus_task.c.
References current_task_index, ICARUS_MAX_TASKS, num_created_tasks, task_list, and task_start().
Referenced by main().
os_task_suicide()
void os_task_suicide (void)
Terminate current task (suicide)
Convenience function to kill the currently running task. Equivalent to os_kill_process(current_task_index).
Definition at line 498 of file icarus_task.c.
References current_task_index, os_kill_process(), and task_list.
os_yield()
void os_yield (void)
Voluntarily yield CPU to scheduler.
Triggers a context switch to the next ready task. The current task is placed in READY state and will be scheduled again.
Note
This function is placed in ITCM for zero wait-state execution.
Implementation:
Sets PendSV pending bit to trigger context switch at lowest interrupt priority, ensuring clean stack state.
See also
ARMv7-M Architecture Reference Manual, Section B1.5.14 (PendSV)
Definition at line 396 of file icarus_task.c.
References current_task_ticks_remaining, and ticks_per_task.
Referenced by os_exit_task(), os_idle_task(), os_kill_process(), and task_active_sleep().
os_yield_pendsv()
void os_yield_pendsv (void) extern
Context switch handler (called from PendSV)
See also
Core/Src/icarus/context_switch.s
pipe_dequeue()
bool pipe_dequeue (uint8_t pipe_idx, uint8_t * message, uint8_t message_bytes)
Dequeue message from pipe.
Blocks if insufficient data until message is available.
Parameters
[in] pipe_idx Pipe index
[out] message Buffer to receive message data
[in] message_bytes Number of bytes to dequeue
Return values
true Message dequeued successfully
false Invalid parameters or pipe not initialized
Note
This function is placed in ITCM for zero wait-state execution.
Definition at line 697 of file icarus_task.c.
References icarus_pipe_t::buffer, icarus_pipe_t::count, icarus_pipe_t::dequeue_idx, enter_critical(), exit_critical(), ICARUS_MAX_MESSAGE_QUEUES, icarus_pipe_t::max_count, message_pipe_list, os_tick_count, scheduler_enabled, task_active_sleep(), and icarus_pipe_t::tick_updated_at.
pipe_enqueue()
bool pipe_enqueue (uint8_t pipe_idx, uint8_t * message, uint8_t message_bytes)
Enqueue message to pipe.
Blocks if insufficient space until room is available.
Parameters
[in] pipe_idx Pipe index
[in] message Pointer to message data
[in] message_bytes Number of bytes to enqueue
Return values
true Message enqueued successfully
false Invalid parameters or pipe not initialized
Note
This function is placed in ITCM for zero wait-state execution.
Definition at line 660 of file icarus_task.c.
References icarus_pipe_t::buffer, icarus_pipe_t::count, icarus_pipe_t::enqueue_idx, enter_critical(), exit_critical(), ICARUS_MAX_MESSAGE_QUEUES, icarus_pipe_t::max_count, message_pipe_list, os_tick_count, scheduler_enabled, task_active_sleep(), and icarus_pipe_t::tick_updated_at.
pipe_get_count()
uint8_t pipe_get_count (uint8_t pipe_idx)
Get current byte count in pipe.
Parameters
[in] pipe_idx Pipe index
Returns
Current byte count, or 0 if invalid/uninitialized
Definition at line 732 of file icarus_task.c.
References icarus_pipe_t::count, ICARUS_MAX_MESSAGE_QUEUES, and message_pipe_list.
pipe_get_max_count()
uint8_t pipe_get_max_count (uint8_t pipe_idx)
Get pipe capacity.
Parameters
[in] pipe_idx Pipe index
Returns
Maximum capacity in bytes, or 0 if invalid/uninitialized
Definition at line 741 of file icarus_task.c.
References ICARUS_MAX_MESSAGE_QUEUES, icarus_pipe_t::max_count, and message_pipe_list.
pipe_init()
bool pipe_init (uint8_t pipe_idx, uint8_t pipe_capacity_bytes)
Initialize a message pipe.
Parameters
[in] pipe_idx Pipe index (0 to ICARUS_MAX_MESSAGE_QUEUES-1)
[in] pipe_capacity_bytes Maximum bytes the pipe can hold
Return values
true Pipe initialized successfully
false Invalid index, capacity=0, or pipe already in use
Definition at line 641 of file icarus_task.c.
References __init_pipe(), enter_critical(), exit_critical(), ICARUS_MAX_MESSAGE_BYTES, ICARUS_MAX_MESSAGE_QUEUES, and message_pipe_list.
semaphore_consume()
bool semaphore_consume (uint8_t semaphore_idx)
Decrement semaphore count (P operation / wait)
Blocks if count == 0 until semaphore is signaled.
Parameters
[in] semaphore_idx Semaphore index
Return values
true Operation successful
false Invalid index or semaphore not initialized
Note
This function is placed in ITCM for zero wait-state execution.
Definition at line 599 of file icarus_task.c.
References icarus_semaphore_t::count, enter_critical(), exit_critical(), ICARUS_MAX_SEMAPHORES, os_tick_count, semaphore_list, task_active_sleep(), and icarus_semaphore_t::tick_updated_at.
semaphore_feed()
bool semaphore_feed (uint8_t semaphore_idx)
Increment semaphore count (V operation / signal)
Blocks if count == max_count until space is available.
Parameters
[in] semaphore_idx Semaphore index
Return values
true Operation successful
false Invalid index or semaphore not initialized
Note
This function is placed in ITCM for zero wait-state execution.
Definition at line 578 of file icarus_task.c.
References icarus_semaphore_t::count, enter_critical(), exit_critical(), ICARUS_MAX_SEMAPHORES, os_tick_count, semaphore_list, task_active_sleep(), and icarus_semaphore_t::tick_updated_at.
semaphore_get_count()
uint32_t semaphore_get_count (uint8_t semaphore_idx)
Get current semaphore count.
Parameters
[in] semaphore_idx Semaphore index
Returns
Current count, or 0 if invalid/uninitialized
Definition at line 619 of file icarus_task.c.
References icarus_semaphore_t::count, ICARUS_MAX_SEMAPHORES, and semaphore_list.
semaphore_get_max_count()
uint32_t semaphore_get_max_count (uint8_t semaphore_idx)
Get semaphore maximum count.
Parameters
[in] semaphore_idx Semaphore index
Returns
Maximum count, or 0 if invalid/uninitialized
Definition at line 628 of file icarus_task.c.
References ICARUS_MAX_SEMAPHORES, icarus_semaphore_t::max_count, and semaphore_list.
semaphore_init()
bool semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Initialize a counting semaphore.
Parameters
[in] semaphore_idx Semaphore index (0 to ICARUS_MAX_SEMAPHORES-1)
[in] semaphore_count Initial count (also sets max_count)
Return values
true Semaphore initialized successfully
false Invalid index, count=0, or semaphore already in use
Definition at line 562 of file icarus_task.c.
References __init_sem(), enter_critical(), exit_critical(), and semaphore_list.
start_cold_task()
void start_cold_task (icarus_task_t * task) extern
Start execution of a cold (never-run) task.
Parameters
task Pointer to task control block
See also
Core/Src/icarus/context_switch.s
Referenced by task_start().
task_active_sleep()
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified number of ticks (non-blocking)
Blocks the current task for the specified duration while allowing other tasks to run. This is the preferred sleep method.
Parameters
[in] ticks Number of SysTick intervals to sleep
Returns
Actual number of ticks elapsed (may be >= requested due to scheduling)
Note
This function is placed in ITCM for zero wait-state execution.
Example:
// Sleep for approximately 100ms (at 1ms tick rate)
uint32_t actual = task_active_sleep(100);
Definition at line 402 of file icarus_task.c.
References current_task_index, icarus_task_t::global_tick_paused, os_tick_count, os_yield(), task_list, icarus_task_t::task_state, TASK_STATE_BLOCKED, and icarus_task_t::ticks_to_pause.
Referenced by LED_Blink(), os_heartbeat_task(), pipe_dequeue(), pipe_enqueue(), semaphore_consume(), and semaphore_feed().
task_blocking_sleep()
uint32_t task_blocking_sleep (uint32_t ticks)
Sleep with interrupts disabled (blocking)
Busy-waits for the specified duration with scheduler disabled. Use sparingly as this blocks all other tasks.
Parameters
[in] ticks Number of SysTick intervals to wait
Returns
Actual number of ticks elapsed
Warning
This function disables the scheduler! Use only when absolutely necessary (e.g., hardware timing requirements).
Definition at line 411 of file icarus_task.c.
References enter_critical(), exit_critical(), and task_busy_wait().
Referenced by __io_putchar().
task_busy_wait()
uint32_t task_busy_wait (uint32_t ticks)
Busy-wait for specified ticks (must be in critical section)
Low-level busy-wait loop. Caller must already be in critical section.
Parameters
[in] ticks Number of ticks to wait
Returns
Actual number of ticks elapsed
Precondition
Must be called from within a critical section
Definition at line 419 of file icarus_task.c.
References os_tick_count.
Referenced by task_blocking_sleep().
task_start()
static void task_start (icarus_task_t * task) static
Start a cold task (internal)
Parameters
task Task to start
Definition at line 391 of file icarus_task.c.
References start_cold_task().
Referenced by os_start().
Variable Documentation
stack_pool
uint32_t stack_pool[128][512] static
Static stack pool for all tasks.
Note
Placed in RAM_D1 (512KB available) With ICARUS_MAX_TASKS=128 and ICARUS_STACK_WORDS=512: 128 × 512 × 4 = 256KB
Definition at line 168 of file icarus_task.c.
Referenced by os_register_task().