ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Src/main.c File Reference
main.c File Reference
ICARUS OS Application Entry Point.
#include "icarus/icarus_task.h"
#include "bsp/bsp_led.h"
#include "bsp/retarget_hal.h"
#include "demo_tasks.h"
#include "stress_test.h"
#include <stdio.h>
Macros
#define ENABLE_STRESS_TEST 1
Enable stress testing mode.
#define ANSI_SHOW_CURSOR()
ANSI escape code to show cursor (used in error path)
Functions
int main (void)
Application entry point.
Detailed Description
ICARUS OS Application Entry Point.
Version
0.1.0
Main entry point for the ICARUS Real-Time Operating System. Initializes hardware, registers demo/stress test tasks, and starts the kernel scheduler.
Boot Sequence:
hal_init() - Hardware initialization (clocks, peripherals)
os_init() - Kernel initialization (task pools, system tasks)
demo_tasks_init() - Register demo producer/consumer tasks
stress_test_init() - Register stress test tasks (if enabled)
os_start() - Start scheduler (never returns)
Configuration:
Set ENABLE_STRESS_TEST to 1 for stress testing, 0 for demo mode only.
See also
docs/do178c/design/SDD.md Section 2 - System Architecture
Author
Souham Biswas
Date
2025
Copyright
Copyright 2025 Souham Biswas https://github.com/ironhide23586/icarus-os-core Licensed under the Apache License, Version 2.0
Definition in file main.c.
Macro Definition Documentation
ANSI_SHOW_CURSOR
#define ANSI_SHOW_CURSOR ()
Value:
printf("\033[?25h")
ANSI escape code to show cursor (used in error path)
Definition at line 48 of file main.c.
Referenced by main().
ENABLE_STRESS_TEST
#define ENABLE_STRESS_TEST 1
Enable stress testing mode.
Note
Set to 1 to enable stress test tasks, 0 for demo mode only
Definition at line 45 of file main.c.
Function Documentation
main()
int main (void)
Application entry point.
Initializes the system and starts the ICARUS kernel. This function should never return under normal operation.
Returns
int Never returns (infinite loop on error)
Execution Flow:
Initialize hardware abstraction layer
Initialize ICARUS kernel
Register demo tasks (producer/consumer patterns)
Register stress test tasks (if enabled)
Start scheduler (does not return)
Error handler (only reached on failure)
Warning
If this function returns, a critical error has occurred. The error path blinks the LED rapidly to indicate failure.
Definition at line 73 of file main.c.
References ANSI_SHOW_CURSOR, hal_init(), LED_Blink(), os_init(), and os_start().