ICARUS OS: Core/Inc/bsp/retarget_hal.h File Reference
retarget_hal.h File Reference
ICARUS OS Hardware Abstraction Layer Interface.
#include "main.h"
#include "i2c.h"
#include "rtc.h"
#include "spi.h"
#include "tim.h"
#include "usb_device.h"
#include "gpio.h"
#include "lcd.h"
#include "lsm9ds1_reg.h"
Macros
#define IMU_ADDRESS 0x6B
I2C address for LSM9DS1 IMU (accelerometer/gyroscope)
Functions
void hal_init (void)
Initialize all hardware abstraction layer components.
void LED_Blink (uint32_t Hdelay, uint32_t Ldelay)
Blink LED with specified on/off timing.
void LED_On (void)
Turn LED on (active high)
void LED_Off (void)
Turn LED off.
Detailed Description
ICARUS OS Hardware Abstraction Layer Interface.
Version
0.1.0
Provides hardware initialization and low-level platform services for the STM32H750VBT6 target.
Target Hardware:
MCU: STM32H750VBT6 (ARM Cortex-M7 @ 480MHz)
Board: WeAct Studio STM32H750VBT6 Core Board
LED: PE3 (active high)
IMU: LSM9DS1 on I2C2 (address 0x6B)
See also
STM32H750 Reference Manual RM0433
Author
Souham Biswas
Date
2026
Copyright
Copyright (c) 2026 ICARUS Project https://github.com/ironhide23586/icarus-os-core Licensed under MIT License
Definition in file retarget_hal.h.
Macro Definition Documentation
IMU_ADDRESS
#define IMU_ADDRESS 0x6B
I2C address for LSM9DS1 IMU (accelerometer/gyroscope)
Definition at line 51 of file retarget_hal.h.
Referenced by platform_read(), and platform_write().
Function Documentation
hal_init()
void hal_init (void)
Initialize all hardware abstraction layer components.
Configures MPU, caches, clocks, and all peripherals. Must be called before os_init().
Precondition
None (called at system startup)
Postcondition
All hardware ready for kernel initialization
Master initialization function that configures all hardware:
Vector table relocation (if running from QSPI)
MPU configuration for memory protection
CPU cache enablement
HAL library initialization
System clock configuration (480MHz)
GPIO initialization
RTC initialization
SPI4 initialization (LCD)
TIM1 initialization (PWM)
I2C2 initialization (IMU)
USB CDC initialization
Precondition
None (called at system startup)
Postcondition
All hardware ready for kernel initialization
Note
Must be called before os_init()
USB may take up to 1 second to enumerate on host
See also
SystemClock_Config() for clock tree details
Definition at line 261 of file retarget_hal.c.
References CPU_CACHE_Enable(), MPU_Config(), MX_GPIO_Init(), MX_I2C2_Init(), MX_RTC_Init(), MX_SPI4_Init(), MX_TIM1_Init(), MX_USB_DEVICE_Init(), and SystemClock_Config().
Referenced by main().
LED_Blink()
void LED_Blink (uint32_t Hdelay, uint32_t Ldelay)
Blink LED with specified on/off timing.
Parameters
[in] Hdelay LED on duration in OS ticks
[in] Ldelay LED off duration in OS ticks
Note
Uses task_active_sleep() - must be called from task context
Blink LED with specified timing.
Turns LED on for specified duration, then off for specified duration. Uses task_active_sleep() for non-blocking delays.
Parameters
[in] Hdelay LED on duration in OS ticks
[in] Ldelay LED off duration in OS ticks
Precondition
GPIO must be initialized (MX_GPIO_Init called)
Must be called from task context (uses task_active_sleep)
Note
Total blink period = Hdelay + Ldelay ticks
Definition at line 153 of file retarget_hal.c.
LED_Off()
void LED_Off (void)
Turn LED off.
Sets PE3 GPIO pin low to turn off the onboard LED.
Precondition
GPIO must be initialized
Definition at line 178 of file retarget_hal.c.
LED_On()
void LED_On (void)
Turn LED on (active high)
Turn LED on.
Sets PE3 GPIO pin high to illuminate the onboard LED.
Precondition
GPIO must be initialized
Definition at line 167 of file retarget_hal.c.