ICARUS OS: Core/Src/bsp/retarget_hal.c File Reference
retarget_hal.c File Reference
ICARUS OS Hardware Abstraction Layer Implementation.
#include "retarget_hal.h"
Functions
static void SystemClock_Config (void)
Configure system clocks for 480MHz operation.
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified ticks while allowing other tasks to run.
int32_t platform_write (void *handle, uint8_t reg, const uint8_t *bufp, uint16_t len)
Platform write function for LSM9DS1 IMU driver.
int32_t platform_read (void *handle, uint8_t reg, uint8_t *bufp, uint16_t len)
Platform read function for LSM9DS1 IMU driver.
static void MPU_Config (void)
Configure Memory Protection Unit for QSPI flash access.
static void CPU_CACHE_Enable (void)
Enable CPU instruction and data caches.
void LED_Blink (uint32_t Hdelay, uint32_t Ldelay)
Blink LED with specified on/off timing.
void LED_On (void)
Turn LED on (active high)
void LED_Off (void)
Turn LED off.
void hal_init (void)
Initialize all hardware abstraction layer components.
Detailed Description
ICARUS OS Hardware Abstraction Layer Implementation.
Version
0.1.0
Provides hardware initialization and low-level platform services for the STM32H750VBT6 target. Includes:
MPU configuration for QSPI flash access
CPU cache enablement (I-Cache, D-Cache)
System clock configuration (480MHz)
Peripheral initialization
LED control functions
I2C platform read/write for IMU
Clock Configuration:
SYSCLK: 480 MHz (from PLL)
HCLK: 240 MHz (AHB)
APB1/APB2/APB3/APB4: 120 MHz
HSE: 25 MHz external crystal
LSE: 32.768 kHz for RTC
Memory Protection:
Region 0: QSPI 256MB - No access (background)
Region 1: QSPI 8MB - Read-only, cacheable, executable
See also
STM32H750 Reference Manual RM0433
docs/do178c/design/SDD.md Section 3 - Hardware Abstraction
Author
Souham Biswas
Date
2026
Copyright
Copyright (c) 2026 ICARUS Project https://github.com/ironhide23586/icarus-os-core Licensed under MIT License
Definition in file retarget_hal.c.
Function Documentation
CPU_CACHE_Enable()
static void CPU_CACHE_Enable (void) static
Enable CPU instruction and data caches.
Enables both I-Cache and D-Cache for improved performance. Must be called after MPU configuration to ensure proper cacheability attributes are in effect.
Precondition
MPU_Config() must be called first
Postcondition
I-Cache and D-Cache enabled
Note
Cache coherency must be managed for DMA operations
See also
ARMv7-M Architecture Reference Manual, Section B2.2 (Caches)
Definition at line 126 of file retarget_hal.c.
Referenced by hal_init().
hal_init()
void hal_init (void)
Initialize all hardware abstraction layer components.
Master initialization function that configures all hardware:
Vector table relocation (if running from QSPI)
MPU configuration for memory protection
CPU cache enablement
HAL library initialization
System clock configuration (480MHz)
GPIO initialization
RTC initialization
SPI4 initialization (LCD)
TIM1 initialization (PWM)
I2C2 initialization (IMU)
USB CDC initialization
Precondition
None (called at system startup)
Postcondition
All hardware ready for kernel initialization
Note
Must be called before os_init()
USB may take up to 1 second to enumerate on host
See also
SystemClock_Config() for clock tree details
Definition at line 261 of file retarget_hal.c.
References CPU_CACHE_Enable(), MPU_Config(), MX_GPIO_Init(), MX_I2C2_Init(), MX_RTC_Init(), MX_SPI4_Init(), MX_TIM1_Init(), MX_USB_DEVICE_Init(), and SystemClock_Config().
Referenced by main().
LED_Blink()
void LED_Blink (uint32_t Hdelay, uint32_t Ldelay)
Blink LED with specified on/off timing.
Blink LED with specified timing.
Turns LED on for specified duration, then off for specified duration. Uses task_active_sleep() for non-blocking delays.
Parameters
[in] Hdelay LED on duration in OS ticks
[in] Ldelay LED off duration in OS ticks
Precondition
GPIO must be initialized (MX_GPIO_Init called)
Must be called from task context (uses task_active_sleep)
Note
Total blink period = Hdelay + Ldelay ticks
Definition at line 153 of file retarget_hal.c.
References E3_GPIO_Port, E3_Pin, and task_active_sleep().
Referenced by main(), and os_heartbeat_task().
LED_Off()
void LED_Off (void)
Turn LED off.
Sets PE3 GPIO pin low to turn off the onboard LED.
Precondition
GPIO must be initialized
Definition at line 178 of file retarget_hal.c.
References E3_GPIO_Port, and E3_Pin.
Referenced by os_heartbeat_task().
LED_On()
void LED_On (void)
Turn LED on (active high)
Turn LED on.
Sets PE3 GPIO pin high to illuminate the onboard LED.
Precondition
GPIO must be initialized
Definition at line 167 of file retarget_hal.c.
References E3_GPIO_Port, and E3_Pin.
Referenced by os_heartbeat_task().
MPU_Config()
static void MPU_Config (void) static
Configure Memory Protection Unit for QSPI flash access.
Sets up two MPU regions for QSPI memory-mapped flash:
Region 0: 256MB background region with no access (catches stray accesses)
Region 1: 8MB overlay for actual flash with read-only, cacheable access
Region Configuration:
Region Base Size Access Cache Execute
0 0x90000000 256MB No Access None No
1 0x90000000 8MB Priv RO WT Cache Yes
Note
Must be called before enabling caches
Uses privileged default memory map for non-configured regions
See also
ARMv7-M Architecture Reference Manual, Section B3.5 (MPU)
STM32H750 Reference Manual RM0433, Section 2.3.4
Definition at line 73 of file retarget_hal.c.
Referenced by hal_init().
platform_read()
int32_t platform_read (void * handle, uint8_t reg, uint8_t * bufp, uint16_t len)
Platform read function for LSM9DS1 IMU driver.
Platform read function for IMU driver.
Reads data from IMU register via I2C. Used by the LSM9DS1 driver library for sensor data acquisition.
Parameters
[in] handle I2C handle (cast to I2C_HandleTypeDef*)
[in] reg Register address to read
[out] bufp Pointer to receive buffer
[in] len Number of bytes to read
Returns
0 on success (HAL status ignored for simplicity)
Note
Uses blocking I2C transfer with HAL_MAX_DELAY timeout
Definition at line 227 of file retarget_hal.c.
References IMU_ADDRESS.
platform_write()
int32_t platform_write (void * handle, uint8_t reg, const uint8_t * bufp, uint16_t len)
Platform write function for LSM9DS1 IMU driver.
Platform write function for IMU driver.
Writes data to IMU register via I2C. Used by the LSM9DS1 driver library for register configuration.
Parameters
[in] handle I2C handle (cast to I2C_HandleTypeDef*)
[in] reg Register address to write
[in] bufp Pointer to data buffer
[in] len Number of bytes to write
Returns
0 on success (HAL status ignored for simplicity)
Note
Uses blocking I2C transfer with HAL_MAX_DELAY timeout
Definition at line 201 of file retarget_hal.c.
References IMU_ADDRESS.
SystemClock_Config()
void SystemClock_Config (void) static
Configure system clocks for 480MHz operation.
Configures the complete clock tree:
HSE: 25MHz external crystal
LSE: 32.768kHz for RTC
HSI48: 48MHz for USB
PLL: 480MHz SYSCLK from HSE
PLL Configuration:
Source: HSE (25MHz)
PLLM: 5 (VCO input = 5MHz)
PLLN: 96 (VCO output = 480MHz)
PLLP: 2 (SYSCLK = 480MHz)
Bus Clocks:
Bus Divider Frequency
SYSCLK /1 480 MHz
HCLK /2 240 MHz
APB1 /1 120 MHz
APB2 /1 120 MHz
APB3 /1 120 MHz
APB4 /1 120 MHz
Note
Calls Error_Handler() on configuration failure
See also
STM32H750 Reference Manual RM0433, Section 8 (RCC)
Supply configuration update enable
< Core domains are supplied from the LDO
Configure the main internal regulator output voltage
Configure LSE Drive Capability
< LSE medium high drive capability
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
< Clock range frequency between 4 and 8 MHz
Initializes the CPU, AHB and APB buses clocks
< FLASH One Latency cycle
Definition at line 332 of file retarget_hal.c.
References Error_Handler().
Referenced by hal_init().
task_active_sleep()
uint32_t task_active_sleep (uint32_t ticks) extern
Sleep for specified ticks while allowing other tasks to run.
Sleep for specified number of ticks (non-blocking)
Puts the current task into BLOCKED state for the specified number of ticks. The scheduler will skip this task until the sleep period expires, allowing other tasks to execute.
This is the preferred sleep method for cooperative multitasking as it does not waste CPU cycles. The task is automatically returned to READY state by the scheduler when ticks expire.
Placed in ITCM for zero wait-state execution.
Parameters
ticks Number of ticks to sleep (1 tick = 1ms at 1kHz)
Returns
uint32_t Actual ticks elapsed (may be >= requested due to scheduling latency)
Precondition
Scheduler must be running
Called from task context (not ISR)
Postcondition
Task state temporarily set to TASK_STATE_BLOCKED
Task resumes after at least 'ticks' have elapsed
Note
Minimum sleep is 1 tick; 0 is treated as immediate yield
Actual sleep may be longer due to higher-priority tasks
See also
task_blocking_sleep() for non-preemptible sleep
task_busy_wait() for spin-wait delay
Example:
// Blink LED at 1Hz
while (1) {
    LED_On();
    task_active_sleep(500);  // 500ms on
    LED_Off();
    task_active_sleep(500);  // 500ms off
}
Definition at line 707 of file icarus_task.c.
Referenced by LED_Blink(), os_heartbeat_task(), pipe_dequeue(), pipe_enqueue(), semaphore_consume(), and semaphore_feed().