ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Inc/icarus/scheduler.h File Reference
scheduler.h File Reference
ICARUS Scheduler - Task Scheduling and Timing.
#include <stdint.h>
Functions
void os_yield (void)
Voluntarily yield CPU to scheduler.
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified ticks (cooperative)
uint32_t task_blocking_sleep (uint32_t ticks)
Sleep with scheduler disabled (blocking)
uint32_t task_busy_wait (uint32_t ticks)
Busy-wait for specified ticks.
uint32_t os_get_tick_count (void)
Get current system tick count.
uint8_t os_get_running_task_count (void)
Get number of active tasks.
const char * os_get_current_task_name (void)
Get name of currently executing task.
uint32_t os_get_task_ticks_remaining (void)
Get remaining ticks in current time slice.
const char * os_get_task_name (uint8_t task_idx)
Get task name by index (safe from unprivileged mode)
uint8_t os_get_num_created_tasks (void)
Get number of created tasks (safe from unprivileged mode)
uint8_t os_is_running (void)
Check if OS is running (safe from unprivileged mode)
void __os_yield (void)
Privileged implementation of os_yield.
uint32_t __task_active_sleep (uint32_t ticks)
Privileged implementation of task_active_sleep.
uint32_t __task_blocking_sleep (uint32_t ticks)
Privileged implementation of task_blocking_sleep.
uint32_t __task_busy_wait (uint32_t ticks)
Privileged implementation of task_busy_wait.
uint32_t __os_get_tick_count (void)
Privileged implementation of os_get_tick_count.
uint8_t __os_get_running_task_count (void)
Privileged implementation of os_get_running_task_count.
const char * __os_get_current_task_name (void)
Privileged implementation of os_get_current_task_name.
uint32_t __os_get_task_ticks_remaining (void)
Privileged implementation of os_get_task_ticks_remaining.
const char * __os_get_task_name (uint8_t task_idx)
Privileged implementation of os_get_task_name.
uint8_t __os_get_num_created_tasks (void)
Privileged implementation of os_get_num_created_tasks.
uint8_t __os_is_running (void)
Privileged implementation of os_is_running.
Detailed Description
ICARUS Scheduler - Task Scheduling and Timing.
Version
0.1.0
Task scheduling, yielding, and sleep functions.
Author
Souham Biswas
Date
2025
Copyright
Copyright 2025 Souham Biswas https://github.com/ironhide23586/icarus-os-core Licensed under the Apache License, Version 2.0
Definition in file scheduler.h.
Function Documentation
__os_get_current_task_name()
const char * __os_get_current_task_name (void)
Privileged implementation of os_get_current_task_name.
Note
Internal function - use os_get_current_task_name() wrapper
Copies name from DTCM to RAM_D1 buffer for unprivileged access
Definition at line 65 of file scheduler.c.
References current_task_index, ICARUS_MAX_TASK_NAME_LEN, icarus_task_t::name, num_created_tasks, task_list, and task_name_buffer.
Referenced by os_get_current_task_name(), and SVC_Handler_C().
__os_get_num_created_tasks()
uint8_t __os_get_num_created_tasks (void)
Privileged implementation of os_get_num_created_tasks.
Note
Internal function - use os_get_num_created_tasks() wrapper
Runs in SVC handler — reads num_created_tasks from DTCM in privileged mode
Definition at line 342 of file kernel.c.
References num_created_tasks.
Referenced by os_get_num_created_tasks(), and SVC_Handler_C().
__os_get_running_task_count()
uint8_t __os_get_running_task_count (void)
Privileged implementation of os_get_running_task_count.
Note
Internal function - use os_get_running_task_count() wrapper
Definition at line 56 of file scheduler.c.
References running_task_count.
Referenced by os_get_running_task_count(), and SVC_Handler_C().
__os_get_task_name()
const char * __os_get_task_name (uint8_t task_idx)
Privileged implementation of os_get_task_name.
Note
Internal function - use os_get_task_name() wrapper
Runs in SVC handler — reads task_list from DTCM in privileged mode
Copies name to RAM_D1 buffer to allow unprivileged access
Definition at line 314 of file kernel.c.
References ICARUS_MAX_TASK_NAME_LEN, icarus_task_t::name, num_created_tasks, and task_list.
Referenced by os_get_task_name(), and SVC_Handler_C().
__os_get_task_ticks_remaining()
uint32_t __os_get_task_ticks_remaining (void)
Privileged implementation of os_get_task_ticks_remaining.
Note
Internal function - use os_get_task_ticks_remaining() wrapper
Definition at line 86 of file scheduler.c.
References current_task_ticks_remaining.
Referenced by os_get_task_ticks_remaining(), and SVC_Handler_C().
__os_get_tick_count()
uint32_t __os_get_tick_count (void)
Privileged implementation of os_get_tick_count.
Note
Internal function - use os_get_tick_count() wrapper
Definition at line 48 of file scheduler.c.
References os_tick_count.
Referenced by os_get_tick_count(), and SVC_Handler_C().
__os_is_running()
uint8_t __os_is_running (void)
Privileged implementation of os_is_running.
Note
Internal function - use os_is_running() wrapper
Runs in SVC handler — reads os_running from DTCM in privileged mode
Definition at line 351 of file kernel.c.
References os_running.
Referenced by os_is_running(), and SVC_Handler_C().
__os_yield()
void __os_yield (void)
Privileged implementation of os_yield.
Note
Internal function - use os_yield() wrapper
Definition at line 98 of file scheduler.c.
References current_task_ticks_remaining, and ticks_per_task.
Referenced by __os_exit_task(), __os_kill_process(), __task_active_sleep(), os_yield(), and SVC_Handler_C().
__task_active_sleep()
uint32_t __task_active_sleep (uint32_t ticks)
Privileged implementation of task_active_sleep.
Note
Internal function - use task_active_sleep() wrapper
Definition at line 107 of file scheduler.c.
References __os_yield(), current_task_index, icarus_task_t::global_tick_paused, os_tick_count, task_list, icarus_task_t::task_state, TASK_STATE_BLOCKED, and icarus_task_t::ticks_to_pause.
Referenced by SVC_Handler_C(), and task_active_sleep().
__task_blocking_sleep()
uint32_t __task_blocking_sleep (uint32_t ticks)
Privileged implementation of task_blocking_sleep.
Note
Internal function - use task_blocking_sleep() wrapper
Spin-wait calls public SVC wrappers — only safe from thread mode
Definition at line 120 of file scheduler.c.
References enter_critical(), exit_critical(), and task_busy_wait().
Referenced by task_blocking_sleep().
__task_busy_wait()
uint32_t __task_busy_wait (uint32_t ticks)
Privileged implementation of task_busy_wait.
Note
Internal function - use task_busy_wait() wrapper
Uses os_get_tick_count() SVC gate — safe with DTCM priv-only
Definition at line 132 of file scheduler.c.
References os_get_tick_count(), and os_tick_count.
Referenced by task_busy_wait().
os_get_current_task_name()
const char * os_get_current_task_name (void)
Get name of currently executing task.
Returns
Task name string or "unknown"
Definition at line 307 of file svc.c.
os_get_num_created_tasks()
uint8_t os_get_num_created_tasks (void)
Get number of created tasks (safe from unprivileged mode)
Returns
Number of tasks registered with os_register_task()
Note
Uses SVC to read num_created_tasks from DTCM in privileged mode
Get number of created tasks (safe from unprivileged mode)
Returns
Number of tasks registered with os_register_task()
Note
Safe to call from unprivileged mode once DTCM is priv-only
Definition at line 853 of file svc.c.
References __os_get_num_created_tasks(), and SVC_GET_NUM_TASKS.
Referenced by display_init().
os_get_running_task_count()
uint8_t os_get_running_task_count (void)
Get number of active tasks.
Returns
Count of tasks in RUNNING/READY/BLOCKED state
Definition at line 326 of file svc.c.
References __os_get_running_task_count(), and SVC_OS_GET_RUNNING_TASK_COUNT.
os_get_task_name()
const char * os_get_task_name (uint8_t task_idx)
Get task name by index (safe from unprivileged mode)
Parameters
task_idx Task index (0 to num_created_tasks-1)
Returns
Pointer to task name string, or NULL if invalid index
Note
Uses SVC to read task_list from DTCM in privileged mode
Get task name by index (safe from unprivileged mode)
Parameters
task_idx Task index (0 to num_created_tasks-1)
Returns
Pointer to task name string, or NULL if invalid index
Note
Safe to call from unprivileged mode once DTCM is priv-only
Definition at line 831 of file svc.c.
References __os_get_task_name(), and SVC_GET_TASK_NAME.
Referenced by display_init().
os_get_task_ticks_remaining()
uint32_t os_get_task_ticks_remaining (void)
Get remaining ticks in current time slice.
Returns
Ticks remaining before preemption
Definition at line 345 of file svc.c.
References __os_get_task_ticks_remaining(), and SVC_OS_GET_TASK_TICKS_REMAINING.
os_get_tick_count()
uint32_t os_get_tick_count (void)
Get current system tick count.
Returns
Ticks since os_start()
Note
Placed in ITCM for zero wait-state execution
Definition at line 288 of file svc.c.
References __os_get_tick_count(), and SVC_OS_GET_TICK_COUNT.
Referenced by __task_busy_wait().
os_is_running()
uint8_t os_is_running (void)
Check if OS is running (safe from unprivileged mode)
Returns
1 if OS is running, 0 otherwise
Note
Uses SVC to read os_running from DTCM in privileged mode
Returns
1 if OS is running, 0 otherwise
Note
Safe to call from unprivileged mode once DTCM is priv-only
Definition at line 874 of file svc.c.
References __os_is_running(), and SVC_OS_IS_RUNNING.
Referenced by os_heartbeat_task().
os_yield()
void os_yield (void)
Voluntarily yield CPU to scheduler.
Note
Placed in ITCM for zero wait-state execution
Definition at line 243 of file svc.c.
task_active_sleep()
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified ticks (cooperative)
Parameters
ticks Number of ticks to sleep
Returns
Actual ticks elapsed
Note
Placed in ITCM for zero wait-state execution
Sleep for specified ticks (cooperative)
Definition at line 254 of file svc.c.
task_blocking_sleep()
uint32_t task_blocking_sleep (uint32_t ticks)
Sleep with scheduler disabled (blocking)
Parameters
ticks Number of ticks to wait
Returns
Actual ticks elapsed
Warning
Blocks all other tasks!
Sleep with scheduler disabled (blocking)
Definition at line 274 of file svc.c.
References __task_blocking_sleep().
Referenced by __io_putchar().
task_busy_wait()
uint32_t task_busy_wait (uint32_t ticks)
Busy-wait for specified ticks.
Parameters
ticks Number of ticks to wait
Returns
Actual ticks elapsed
Busy-wait for specified ticks.
Definition at line 281 of file svc.c.
References __task_busy_wait().
Referenced by __task_blocking_sleep().