ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Inc/icarus/semaphore.h File Reference
semaphore.h File Reference
ICARUS Semaphore - Counting Semaphores.
#include <stdint.h>
#include <stdbool.h>
Functions
bool semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Initialize a counting semaphore.
bool semaphore_feed (uint8_t semaphore_idx)
Increment semaphore count (V operation / signal)
bool semaphore_consume (uint8_t semaphore_idx)
Decrement semaphore count (P operation / wait)
uint32_t semaphore_get_count (uint8_t semaphore_idx)
Get current semaphore count.
uint32_t semaphore_get_max_count (uint8_t semaphore_idx)
Get semaphore maximum count.
bool sem_can_feed (uint8_t semaphore_idx)
Check if semaphore can accept a feed (SVC call gate)
bool sem_can_consume (uint8_t semaphore_idx)
Check if semaphore can be consumed (SVC call gate)
void sem_increment (uint8_t semaphore_idx)
Increment semaphore count (SVC call gate)
void sem_decrement (uint8_t semaphore_idx)
Decrement semaphore count (SVC call gate)
bool __semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Privileged implementation of semaphore_init.
bool __semaphore_feed (uint8_t semaphore_idx)
Privileged implementation of semaphore_feed.
bool __semaphore_consume (uint8_t semaphore_idx)
Privileged implementation of semaphore_consume.
uint32_t __semaphore_get_count (uint8_t semaphore_idx)
Privileged implementation of semaphore_get_count.
uint32_t __semaphore_get_max_count (uint8_t semaphore_idx)
Privileged implementation of semaphore_get_max_count.
bool __sem_can_feed (uint8_t semaphore_idx)
Privileged call gate: can semaphore accept a feed?
bool __sem_can_consume (uint8_t semaphore_idx)
Privileged call gate: can semaphore be consumed?
void __sem_increment (uint8_t semaphore_idx)
Privileged write gate: increment semaphore count.
void __sem_decrement (uint8_t semaphore_idx)
Privileged write gate: decrement semaphore count.
Detailed Description
ICARUS Semaphore - Counting Semaphores.
Version
0.1.0
Counting semaphore implementation for task synchronization.
Author
Souham Biswas
Date
2025
Copyright
Copyright 2025 Souham Biswas https://github.com/ironhide23586/icarus-os-core Licensed under the Apache License, Version 2.0
Definition in file semaphore.h.
Function Documentation
__sem_can_consume()
bool __sem_can_consume (uint8_t semaphore_idx)
Privileged call gate: can semaphore be consumed?
Note
Returns true if engaged and count > 0 Used by __semaphore_consume spin loop.
Definition at line 147 of file semaphore.c.
References icarus_semaphore_t::count, ICARUS_MAX_SEMAPHORES, and semaphore_list.
Referenced by sem_can_consume(), and SVC_Handler_C().
__sem_can_feed()
bool __sem_can_feed (uint8_t semaphore_idx)
Privileged call gate: can semaphore accept a feed?
Note
Returns true if engaged and count < max_count Used by __semaphore_feed spin loop to avoid direct DTCM reads from unprivileged thread mode once DTCM is priv-only.
Definition at line 133 of file semaphore.c.
References icarus_semaphore_t::count, ICARUS_MAX_SEMAPHORES, icarus_semaphore_t::max_count, and semaphore_list.
Referenced by sem_can_feed(), and SVC_Handler_C().
__sem_decrement()
void __sem_decrement (uint8_t semaphore_idx)
Privileged write gate: decrement semaphore count.
Note
Called after sem_can_consume() spin loop exits Runs in privileged SVC handler — already atomic, no critical section needed
Definition at line 174 of file semaphore.c.
References icarus_semaphore_t::count, ICARUS_MAX_SEMAPHORES, os_tick_count, semaphore_list, and icarus_semaphore_t::tick_updated_at.
Referenced by sem_decrement(), and SVC_Handler_C().
__sem_increment()
void __sem_increment (uint8_t semaphore_idx)
Privileged write gate: increment semaphore count.
Note
Called after sem_can_feed() spin loop exits Runs in privileged SVC handler — already atomic, no critical section needed
Definition at line 160 of file semaphore.c.
References icarus_semaphore_t::count, ICARUS_MAX_SEMAPHORES, os_tick_count, semaphore_list, and icarus_semaphore_t::tick_updated_at.
Referenced by sem_increment(), and SVC_Handler_C().
__semaphore_consume()
bool __semaphore_consume (uint8_t semaphore_idx)
Privileged implementation of semaphore_consume.
Note
Internal function - use semaphore_consume() wrapper
Spin-wait uses sem_can_consume() SVC gate — safe with DTCM priv-only
Definition at line 81 of file semaphore.c.
References ICARUS_MAX_SEMAPHORES, sem_can_consume(), sem_decrement(), semaphore_list, and task_active_sleep().
Referenced by semaphore_consume().
__semaphore_feed()
bool __semaphore_feed (uint8_t semaphore_idx)
Privileged implementation of semaphore_feed.
Note
Internal function - use semaphore_feed() wrapper
Spin-wait uses sem_can_feed() SVC gate — safe with DTCM priv-only
Definition at line 54 of file semaphore.c.
References ICARUS_MAX_SEMAPHORES, sem_can_feed(), sem_increment(), semaphore_list, and task_active_sleep().
Referenced by semaphore_feed().
__semaphore_get_count()
uint32_t __semaphore_get_count (uint8_t semaphore_idx)
Privileged implementation of semaphore_get_count.
Note
Internal function - use semaphore_get_count() wrapper
Definition at line 107 of file semaphore.c.
References icarus_semaphore_t::count, ICARUS_MAX_SEMAPHORES, and semaphore_list.
Referenced by semaphore_get_count(), and SVC_Handler_C().
__semaphore_get_max_count()
uint32_t __semaphore_get_max_count (uint8_t semaphore_idx)
Privileged implementation of semaphore_get_max_count.
Note
Internal function - use semaphore_get_max_count() wrapper
Definition at line 119 of file semaphore.c.
References ICARUS_MAX_SEMAPHORES, icarus_semaphore_t::max_count, and semaphore_list.
Referenced by semaphore_get_max_count(), and SVC_Handler_C().
__semaphore_init()
bool __semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Privileged implementation of semaphore_init.
Note
Internal function - use semaphore_init() wrapper
Runs in SVC handler — already atomic, no critical section needed
Definition at line 35 of file semaphore.c.
References icarus_semaphore_t::count, icarus_semaphore_t::engaged, icarus_semaphore_t::max_count, os_tick_count, semaphore_list, and icarus_semaphore_t::tick_updated_at.
Referenced by semaphore_init(), and SVC_Handler_C().
sem_can_consume()
bool sem_can_consume (uint8_t semaphore_idx)
Check if semaphore can be consumed (SVC call gate)
Parameters
semaphore_idx Semaphore index
Returns
true if count > 0 and engaged
Note
Uses SVC to read semaphore_list from DTCM in privileged mode
Check if semaphore can be consumed (SVC call gate)
Note
Runs in privileged mode — safe once DTCM is priv-only
Definition at line 675 of file svc.c.
References __sem_can_consume(), and SVC_SEM_CAN_CONSUME.
Referenced by __semaphore_consume().
sem_can_feed()
bool sem_can_feed (uint8_t semaphore_idx)
Check if semaphore can accept a feed (SVC call gate)
Parameters
semaphore_idx Semaphore index
Returns
true if count < max_count and engaged
Note
Uses SVC to read semaphore_list from DTCM in privileged mode
Check if semaphore can accept a feed (SVC call gate)
Note
Runs in privileged mode — safe once DTCM is priv-only
Definition at line 654 of file svc.c.
References __sem_can_feed(), and SVC_SEM_CAN_FEED.
Referenced by __semaphore_feed().
sem_decrement()
void sem_decrement (uint8_t semaphore_idx)
Decrement semaphore count (SVC call gate)
Parameters
semaphore_idx Semaphore index
Note
Uses SVC to write semaphore_list in DTCM from privileged mode
Called after sem_can_consume() spin loop exits
Decrement semaphore count (SVC call gate)
Note
Called after sem_can_consume() spin loop exits
Definition at line 764 of file svc.c.
References __sem_decrement(), and SVC_SEM_DECREMENT.
Referenced by __semaphore_consume().
sem_increment()
void sem_increment (uint8_t semaphore_idx)
Increment semaphore count (SVC call gate)
Parameters
semaphore_idx Semaphore index
Note
Uses SVC to write semaphore_list in DTCM from privileged mode
Called after sem_can_feed() spin loop exits
Increment semaphore count (SVC call gate)
Note
Called after sem_can_feed() spin loop exits
Definition at line 746 of file svc.c.
References __sem_increment(), and SVC_SEM_INCREMENT.
Referenced by __semaphore_feed().
semaphore_consume()
bool semaphore_consume (uint8_t semaphore_idx)
Decrement semaphore count (P operation / wait)
Parameters
semaphore_idx Semaphore index
Returns
true on success
Note
Blocks if count == 0
Placed in ITCM for zero wait-state execution
Decrement semaphore count (P operation / wait)
Definition at line 522 of file svc.c.
References __semaphore_consume().
semaphore_feed()
bool semaphore_feed (uint8_t semaphore_idx)
Increment semaphore count (V operation / signal)
Parameters
semaphore_idx Semaphore index
Returns
true on success
Note
Blocks if count == max_count
Placed in ITCM for zero wait-state execution
Increment semaphore count (V operation / signal)
Definition at line 515 of file svc.c.
References __semaphore_feed().
semaphore_get_count()
uint32_t semaphore_get_count (uint8_t semaphore_idx)
Get current semaphore count.
Parameters
semaphore_idx Semaphore index
Returns
Current count, or 0 if invalid
Definition at line 529 of file svc.c.
References __semaphore_get_count(), and SVC_SEMAPHORE_GET_COUNT.
semaphore_get_max_count()
uint32_t semaphore_get_max_count (uint8_t semaphore_idx)
Get semaphore maximum count.
Parameters
semaphore_idx Semaphore index
Returns
Maximum count, or 0 if invalid
Definition at line 549 of file svc.c.
References __semaphore_get_max_count(), and SVC_SEMAPHORE_GET_MAX_COUNT.
semaphore_init()
bool semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Initialize a counting semaphore.
Parameters
semaphore_idx Semaphore index (0 to ICARUS_MAX_SEMAPHORES-1)
semaphore_count Initial and maximum count
Returns
true on success, false on error
Definition at line 493 of file svc.c.
References __semaphore_init(), and SVC_SEMAPHORE_INIT.