ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Src/bsp/spi.c File Reference
spi.c File Reference
This file provides code for the configuration of the SPI instances.
#include "bsp/spi.h"
#include "bsp/error.h"
Functions
void MX_SPI4_Init (void)
void HAL_SPI_MspInit (SPI_HandleTypeDef *spiHandle)
void HAL_SPI_MspDeInit (SPI_HandleTypeDef *spiHandle)
Variables
SPI_HandleTypeDef hspi4
Detailed Description
This file provides code for the configuration of the SPI instances.
Attention
Copyright (c) 2025 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file spi.c.
Function Documentation
HAL_SPI_MspDeInit()
void HAL_SPI_MspDeInit (SPI_HandleTypeDef * spiHandle)
SPI4 GPIO Configuration PE12 ------> SPI4_SCK PE14 ------> SPI4_MOSI
Definition at line 114 of file spi.c.
HAL_SPI_MspInit()
void HAL_SPI_MspInit (SPI_HandleTypeDef * spiHandle)
Initializes the peripherals clock
SPI4 GPIO Configuration PE12 ------> SPI4_SCK PE14 ------> SPI4_MOSI
< Alternate Function Push Pull Mode
< No Pull-up or Pull-down activation
< Fast speed
Definition at line 73 of file spi.c.
References Error_Handler().
MX_SPI4_Init()
void MX_SPI4_Init (void)
Definition at line 31 of file spi.c.
References Error_Handler(), and hspi4.
Referenced by hal_init().
Variable Documentation
hspi4
SPI_HandleTypeDef hspi4
Definition at line 28 of file spi.c.
Referenced by MX_SPI4_Init().