ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Src/icarus/svc.c File Reference
svc.c File Reference
ICARUS Supervisor Call (SVC) Implementation.
#include "icarus/svc.h"
#include "icarus/kernel.h"
#include "icarus/task.h"
#include "icarus/scheduler.h"
#include "icarus/pipe.h"
#include "icarus/semaphore.h"
Functions
void SVC_Handler_C (uint32_t *stack_frame)
C-level SVC dispatcher called from SVC_Handler assembly trampoline.
void enter_critical (void)
Enter critical section (disable scheduler)
void exit_critical (void)
Exit critical section (re-enable scheduler if outermost)
void os_init (void)
Initialize the ICARUS kernel.
void os_start (void)
Start the ICARUS scheduler.
void os_yield (void)
Voluntarily yield CPU to scheduler.
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified ticks (cooperative, via SVC)
uint32_t task_blocking_sleep (uint32_t ticks)
Blocking sleep — spin-wait in thread mode (cannot run in SVC handler)
uint32_t task_busy_wait (uint32_t ticks)
Busy-wait for specified ticks — spin in thread mode.
uint32_t os_get_tick_count (void)
Get current system tick count.
const char * os_get_current_task_name (void)
Get name of currently executing task.
uint8_t os_get_running_task_count (void)
Get number of active tasks.
uint32_t os_get_task_ticks_remaining (void)
Get remaining ticks in current time slice.
void os_exit_task (void)
Exit current task.
void os_task_suicide (void)
Terminate current task (suicide)
void os_register_task (void(*function)(void), const char *name)
Register a task with the scheduler.
void os_kill_process (uint8_t task_index)
Kill a task by index.
uint32_t * kernel_get_stack (uint8_t task_idx)
Get stack pointer for task index.
uint32_t * kernel_get_data (uint8_t task_idx)
Get data pointer for task index.
void * kernel_protected_data (uint16_t num_words)
Allocate protected data words for current task.
bool semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Initialize a counting semaphore.
bool semaphore_feed (uint8_t semaphore_idx)
Increment semaphore count — spin-wait in thread mode.
bool semaphore_consume (uint8_t semaphore_idx)
Decrement semaphore count — spin-wait in thread mode.
uint32_t semaphore_get_count (uint8_t semaphore_idx)
Get current semaphore count.
uint32_t semaphore_get_max_count (uint8_t semaphore_idx)
Get semaphore maximum count.
bool pipe_init (uint8_t pipe_idx, uint8_t pipe_capacity_bytes)
Initialize a message pipe.
bool pipe_enqueue (uint8_t pipe_idx, uint8_t *message, uint8_t message_bytes)
Enqueue bytes to pipe — spin-wait in thread mode.
bool pipe_dequeue (uint8_t pipe_idx, uint8_t *message, uint8_t message_bytes)
Dequeue bytes from pipe — spin-wait in thread mode.
uint8_t pipe_get_count (uint8_t pipe_idx)
Get current byte count in pipe.
uint8_t pipe_get_max_count (uint8_t pipe_idx)
Get pipe capacity.
bool sem_can_feed (uint8_t semaphore_idx)
Check if semaphore can accept a feed (count < max && engaged)
bool sem_can_consume (uint8_t semaphore_idx)
Check if semaphore can be consumed (count > 0 && engaged)
bool pipe_can_enqueue (uint8_t pipe_idx, uint8_t message_bytes)
Check if pipe has room for message_bytes (free >= bytes && engaged)
bool pipe_can_dequeue (uint8_t pipe_idx, uint8_t message_bytes)
Check if pipe has message_bytes available (count >= bytes && engaged)
void sem_increment (uint8_t semaphore_idx)
Increment semaphore count atomically in privileged mode.
void sem_decrement (uint8_t semaphore_idx)
Decrement semaphore count atomically in privileged mode.
void pipe_write_bytes (uint8_t pipe_idx, uint8_t *message, uint8_t message_bytes)
Write bytes to pipe buffer atomically in privileged mode.
void pipe_read_bytes (uint8_t pipe_idx, uint8_t *message, uint8_t message_bytes)
Read bytes from pipe buffer atomically in privileged mode.
const char * os_get_task_name (uint8_t task_idx)
Get task name by index (read from task_list in privileged mode)
uint8_t os_get_num_created_tasks (void)
Get number of created tasks (read num_created_tasks in privileged mode)
uint8_t os_is_running (void)
Check if OS is running (safe from unprivileged mode)
Detailed Description
ICARUS Supervisor Call (SVC) Implementation.
Version
0.1.0
SVC handler and public wrapper functions for MPU-protected kernel calls. Non-spinning wrappers issue SVC instructions to execute in privileged handler mode. Spinning wrappers (semaphore_feed/consume, pipe_enqueue/dequeue, task_blocking_sleep/busy_wait) call __func directly in thread mode — they cannot run inside the SVC handler because PendSV is lower priority and cannot preempt it.
Author
Souham Biswas
Date
2025
Copyright
Copyright 2025 Souham Biswas https://github.com/ironhide23586/icarus-os-core Licensed under the Apache License, Version 2.0
Definition in file svc.c.
Function Documentation
enter_critical()
void enter_critical (void)
Enter critical section (disable scheduler)
Note
Supports nesting
Definition at line 210 of file svc.c.
References __enter_critical(), and SVC_ENTER_CRITICAL.
Referenced by __task_blocking_sleep().
exit_critical()
void exit_critical (void)
Exit critical section (re-enable scheduler if outermost)
Definition at line 221 of file svc.c.
References __exit_critical(), and SVC_EXIT_CRITICAL.
Referenced by __task_blocking_sleep().
kernel_get_data()
uint32_t * kernel_get_data (uint8_t task_idx)
Get data pointer for task index.
Get data pointer for task index (internal use)
Definition at line 449 of file svc.c.
References __kernel_get_data(), and SVC_KERNEL_GET_DATA.
kernel_get_stack()
uint32_t * kernel_get_stack (uint8_t task_idx)
Get stack pointer for task index.
Get stack pointer for task index (internal use)
Definition at line 429 of file svc.c.
References __kernel_get_stack(), and SVC_KERNEL_GET_STACK.
kernel_protected_data()
void * kernel_protected_data (uint16_t num_words)
Allocate protected data words for current task.
Definition at line 469 of file svc.c.
References __kernel_protected_data(), and SVC_KERNEL_PROTECTED_DATA.
os_exit_task()
void os_exit_task (void)
Exit current task.
Terminate current task normally.
Definition at line 368 of file svc.c.
References __os_exit_task(), and SVC_OS_EXIT_TASK.
Referenced by os_create_task().
os_get_current_task_name()
const char * os_get_current_task_name (void)
Get name of currently executing task.
Returns
Task name string or "unknown"
Definition at line 307 of file svc.c.
References __os_get_current_task_name(), and SVC_OS_GET_CURRENT_TASK_NAME.
Referenced by os_heartbeat_task().
os_get_num_created_tasks()
uint8_t os_get_num_created_tasks (void)
Get number of created tasks (read num_created_tasks in privileged mode)
Get number of created tasks (safe from unprivileged mode)
Returns
Number of tasks registered with os_register_task()
Note
Safe to call from unprivileged mode once DTCM is priv-only
Definition at line 853 of file svc.c.
References __os_get_num_created_tasks(), and SVC_GET_NUM_TASKS.
Referenced by display_init().
os_get_running_task_count()
uint8_t os_get_running_task_count (void)
Get number of active tasks.
Returns
Count of tasks in RUNNING/READY/BLOCKED state
Definition at line 326 of file svc.c.
References __os_get_running_task_count(), and SVC_OS_GET_RUNNING_TASK_COUNT.
os_get_task_name()
const char * os_get_task_name (uint8_t task_idx)
Get task name by index (read from task_list in privileged mode)
Get task name by index (safe from unprivileged mode)
Parameters
task_idx Task index (0 to num_created_tasks-1)
Returns
Pointer to task name string, or NULL if invalid index
Note
Safe to call from unprivileged mode once DTCM is priv-only
Definition at line 831 of file svc.c.
References __os_get_task_name(), and SVC_GET_TASK_NAME.
Referenced by display_init().
os_get_task_ticks_remaining()
uint32_t os_get_task_ticks_remaining (void)
Get remaining ticks in current time slice.
Returns
Ticks remaining before preemption
Definition at line 345 of file svc.c.
References __os_get_task_ticks_remaining(), and SVC_OS_GET_TASK_TICKS_REMAINING.
os_get_tick_count()
uint32_t os_get_tick_count (void)
Get current system tick count.
Returns
Ticks since os_start()
Note
Placed in ITCM for zero wait-state execution
Definition at line 288 of file svc.c.
References __os_get_tick_count(), and SVC_OS_GET_TICK_COUNT.
Referenced by __task_busy_wait().
os_init()
void os_init (void)
Initialize the ICARUS kernel.
Must be called before any other kernel function. Initializes:
Task pool and task list
Semaphore pool
Message pipe pool
System tasks (idle, heartbeat)
Precondition
HAL must be initialized (hal_init() called)
Postcondition
Kernel is ready for task registration
Definition at line 233 of file svc.c.
References __os_init().
Referenced by main().
os_is_running()
uint8_t os_is_running (void)
Check if OS is running (safe from unprivileged mode)
Returns
1 if OS is running, 0 otherwise
Note
Safe to call from unprivileged mode once DTCM is priv-only
Definition at line 874 of file svc.c.
References __os_is_running(), and SVC_OS_IS_RUNNING.
Referenced by os_heartbeat_task().
os_kill_process()
void os_kill_process (uint8_t task_index)
Kill a task by index.
Terminate another task by index.
Definition at line 408 of file svc.c.
References __os_kill_process(), and SVC_OS_KILL_PROCESS.
os_register_task()
void os_register_task (void(* function)(void), const char * name)
Register a task with the scheduler.
Register a task with automatic stack allocation.
Definition at line 390 of file svc.c.
References __os_register_task(), and SVC_OS_REGISTER_TASK.
os_start()
void os_start (void)
Start the ICARUS scheduler.
Begins task execution. This function does not return.
Precondition
os_init() must have been called
At least one task must be registered
Warning
This function never returns!
Definition at line 234 of file svc.c.
References __os_start().
Referenced by main().
os_task_suicide()
void os_task_suicide (void)
Terminate current task (suicide)
Definition at line 379 of file svc.c.
References __os_task_suicide(), and SVC_OS_TASK_SUICIDE.
os_yield()
void os_yield (void)
Voluntarily yield CPU to scheduler.
Note
Placed in ITCM for zero wait-state execution
Definition at line 243 of file svc.c.
References __os_yield(), and SVC_OS_YIELD.
Referenced by os_idle_task().
pipe_can_dequeue()
bool pipe_can_dequeue (uint8_t pipe_idx, uint8_t message_bytes)
Check if pipe has message_bytes available (count >= bytes && engaged)
Check if pipe has data available (SVC call gate)
Note
Runs in privileged mode — safe once DTCM is priv-only
Definition at line 719 of file svc.c.
References __pipe_can_dequeue(), and SVC_PIPE_CAN_DEQUEUE.
Referenced by __pipe_dequeue().
pipe_can_enqueue()
bool pipe_can_enqueue (uint8_t pipe_idx, uint8_t message_bytes)
Check if pipe has room for message_bytes (free >= bytes && engaged)
Check if pipe can accept data (SVC call gate)
Note
Runs in privileged mode — safe once DTCM is priv-only
Definition at line 696 of file svc.c.
References __pipe_can_enqueue(), and SVC_PIPE_CAN_ENQUEUE.
Referenced by __pipe_enqueue().
pipe_dequeue()
bool pipe_dequeue (uint8_t pipe_idx, uint8_t * message, uint8_t message_bytes)
Dequeue bytes from pipe — spin-wait in thread mode.
Dequeue bytes from pipe.
Definition at line 602 of file svc.c.
References __pipe_dequeue().
pipe_enqueue()
bool pipe_enqueue (uint8_t pipe_idx, uint8_t * message, uint8_t message_bytes)
Enqueue bytes to pipe — spin-wait in thread mode.
Enqueue bytes to pipe.
Definition at line 595 of file svc.c.
References __pipe_enqueue().
pipe_get_count()
uint8_t pipe_get_count (uint8_t pipe_idx)
Get current byte count in pipe.
Parameters
pipe_idx Pipe index
Returns
Current count, or 0 if invalid
Definition at line 609 of file svc.c.
References __pipe_get_count(), and SVC_PIPE_GET_COUNT.
pipe_get_max_count()
uint8_t pipe_get_max_count (uint8_t pipe_idx)
Get pipe capacity.
Parameters
pipe_idx Pipe index
Returns
Maximum capacity, or 0 if invalid
Definition at line 629 of file svc.c.
References __pipe_get_max_count(), and SVC_PIPE_GET_MAX_COUNT.
pipe_init()
bool pipe_init (uint8_t pipe_idx, uint8_t pipe_capacity_bytes)
Initialize a message pipe.
Parameters
pipe_idx Pipe index (0 to ICARUS_MAX_MESSAGE_QUEUES-1)
pipe_capacity_bytes Maximum bytes the pipe can hold
Returns
true on success, false on error
Definition at line 573 of file svc.c.
References __pipe_init(), and SVC_PIPE_INIT.
pipe_read_bytes()
void pipe_read_bytes (uint8_t pipe_idx, uint8_t * message, uint8_t message_bytes)
Read bytes from pipe buffer atomically in privileged mode.
Read bytes from pipe (SVC call gate)
Note
Called after pipe_can_dequeue() spin loop exits
Definition at line 803 of file svc.c.
References __pipe_read_bytes(), and SVC_PIPE_READ_BYTES.
Referenced by __pipe_dequeue().
pipe_write_bytes()
void pipe_write_bytes (uint8_t pipe_idx, uint8_t * message, uint8_t message_bytes)
Write bytes to pipe buffer atomically in privileged mode.
Write bytes to pipe (SVC call gate)
Note
Called after pipe_can_enqueue() spin loop exits
Definition at line 782 of file svc.c.
References __pipe_write_bytes(), and SVC_PIPE_WRITE_BYTES.
Referenced by __pipe_enqueue().
sem_can_consume()
bool sem_can_consume (uint8_t semaphore_idx)
Check if semaphore can be consumed (count > 0 && engaged)
Check if semaphore can be consumed (SVC call gate)
Note
Runs in privileged mode — safe once DTCM is priv-only
Definition at line 675 of file svc.c.
References __sem_can_consume(), and SVC_SEM_CAN_CONSUME.
Referenced by __semaphore_consume().
sem_can_feed()
bool sem_can_feed (uint8_t semaphore_idx)
Check if semaphore can accept a feed (count < max && engaged)
Check if semaphore can accept a feed (SVC call gate)
Note
Runs in privileged mode — safe once DTCM is priv-only
Definition at line 654 of file svc.c.
References __sem_can_feed(), and SVC_SEM_CAN_FEED.
Referenced by __semaphore_feed().
sem_decrement()
void sem_decrement (uint8_t semaphore_idx)
Decrement semaphore count atomically in privileged mode.
Decrement semaphore count (SVC call gate)
Note
Called after sem_can_consume() spin loop exits
Definition at line 764 of file svc.c.
References __sem_decrement(), and SVC_SEM_DECREMENT.
Referenced by __semaphore_consume().
sem_increment()
void sem_increment (uint8_t semaphore_idx)
Increment semaphore count atomically in privileged mode.
Increment semaphore count (SVC call gate)
Note
Called after sem_can_feed() spin loop exits
Definition at line 746 of file svc.c.
References __sem_increment(), and SVC_SEM_INCREMENT.
Referenced by __semaphore_feed().
semaphore_consume()
bool semaphore_consume (uint8_t semaphore_idx)
Decrement semaphore count — spin-wait in thread mode.
Decrement semaphore count (P operation / wait)
Definition at line 522 of file svc.c.
References __semaphore_consume().
semaphore_feed()
bool semaphore_feed (uint8_t semaphore_idx)
Increment semaphore count — spin-wait in thread mode.
Increment semaphore count (V operation / signal)
Definition at line 515 of file svc.c.
References __semaphore_feed().
semaphore_get_count()
uint32_t semaphore_get_count (uint8_t semaphore_idx)
Get current semaphore count.
Parameters
semaphore_idx Semaphore index
Returns
Current count, or 0 if invalid
Definition at line 529 of file svc.c.
References __semaphore_get_count(), and SVC_SEMAPHORE_GET_COUNT.
semaphore_get_max_count()
uint32_t semaphore_get_max_count (uint8_t semaphore_idx)
Get semaphore maximum count.
Parameters
semaphore_idx Semaphore index
Returns
Maximum count, or 0 if invalid
Definition at line 549 of file svc.c.
References __semaphore_get_max_count(), and SVC_SEMAPHORE_GET_MAX_COUNT.
semaphore_init()
bool semaphore_init (uint8_t semaphore_idx, uint32_t semaphore_count)
Initialize a counting semaphore.
Parameters
semaphore_idx Semaphore index (0 to ICARUS_MAX_SEMAPHORES-1)
semaphore_count Initial and maximum count
Returns
true on success, false on error
Definition at line 493 of file svc.c.
References __semaphore_init(), and SVC_SEMAPHORE_INIT.
SVC_Handler_C()
void SVC_Handler_C (uint32_t * stack_frame)
C-level SVC dispatcher called from SVC_Handler assembly trampoline.
C-level SVC dispatcher called from SVC_Handler assembly.
Parameters
stack_frame Pointer to exception stack frame (R0-R3, R12, LR, PC, xPSR)
Note
SVC number is extracted from the SVC instruction encoding: The SVC instruction is at [PC - 2], and the immediate is the low byte.
Definition at line 41 of file svc.c.
References __enter_critical(), __exit_critical(), __kernel_get_data(), __kernel_get_stack(), __kernel_protected_data(), __os_exit_task(), __os_get_current_task_name(), __os_get_num_created_tasks(), __os_get_running_task_count(), __os_get_task_name(), __os_get_task_ticks_remaining(), __os_get_tick_count(), __os_is_running(), __os_kill_process(), __os_register_task(), __os_task_suicide(), __os_yield(), __pipe_can_dequeue(), __pipe_can_enqueue(), __pipe_get_count(), __pipe_get_max_count(), __pipe_init(), __pipe_read_bytes(), __pipe_write_bytes(), __sem_can_consume(), __sem_can_feed(), __sem_decrement(), __sem_increment(), __semaphore_get_count(), __semaphore_get_max_count(), __semaphore_init(), __task_active_sleep(), SVC_ENTER_CRITICAL, SVC_EXIT_CRITICAL, SVC_GET_NUM_TASKS, SVC_GET_TASK_NAME, SVC_KERNEL_GET_DATA, SVC_KERNEL_GET_STACK, SVC_KERNEL_PROTECTED_DATA, SVC_OS_EXIT_TASK, SVC_OS_GET_CURRENT_TASK_NAME, SVC_OS_GET_RUNNING_TASK_COUNT, SVC_OS_GET_TASK_TICKS_REMAINING, SVC_OS_GET_TICK_COUNT, SVC_OS_IS_RUNNING, SVC_OS_KILL_PROCESS, SVC_OS_REGISTER_TASK, SVC_OS_TASK_SUICIDE, SVC_OS_YIELD, SVC_PIPE_CAN_DEQUEUE, SVC_PIPE_CAN_ENQUEUE, SVC_PIPE_DEQUEUE, SVC_PIPE_ENQUEUE, SVC_PIPE_GET_COUNT, SVC_PIPE_GET_MAX_COUNT, SVC_PIPE_INIT, SVC_PIPE_READ_BYTES, SVC_PIPE_WRITE_BYTES, SVC_SEM_CAN_CONSUME, SVC_SEM_CAN_FEED, SVC_SEM_DECREMENT, SVC_SEM_INCREMENT, SVC_SEMAPHORE_CONSUME, SVC_SEMAPHORE_FEED, SVC_SEMAPHORE_GET_COUNT, SVC_SEMAPHORE_GET_MAX_COUNT, SVC_SEMAPHORE_INIT, SVC_TASK_ACTIVE_SLEEP, SVC_TASK_BLOCKING_SLEEP, and SVC_TASK_BUSY_WAIT.
task_active_sleep()
uint32_t task_active_sleep (uint32_t ticks)
Sleep for specified ticks (cooperative, via SVC)
Sleep for specified ticks (cooperative)
Definition at line 254 of file svc.c.
References __task_active_sleep(), and SVC_TASK_ACTIVE_SLEEP.
Referenced by __pipe_dequeue(), __pipe_enqueue(), __semaphore_consume(), __semaphore_feed(), LED_Blink(), and os_heartbeat_task().
task_blocking_sleep()
uint32_t task_blocking_sleep (uint32_t ticks)
Blocking sleep — spin-wait in thread mode (cannot run in SVC handler)
Sleep with scheduler disabled (blocking)
Definition at line 274 of file svc.c.
References __task_blocking_sleep().
Referenced by __io_putchar().
task_busy_wait()
uint32_t task_busy_wait (uint32_t ticks)
Busy-wait for specified ticks — spin in thread mode.
Busy-wait for specified ticks.
Definition at line 281 of file svc.c.
References __task_busy_wait().
Referenced by __task_blocking_sleep().