ICARUS OS (Intelligent Cooperative Architecture for Real-time Unified Systems): Core/Src/icarus/task.c File Reference
task.c File Reference
ICARUS Task Management Implementation.
#include "icarus/task.h"
#include "icarus/kernel.h"
#include "icarus/scheduler.h"
#include <string.h>
#include <stdio.h>
Functions
void os_create_task (icarus_task_t *task, void(*function)(void), uint32_t *stack, uint32_t stack_size, uint32_t *data, const char *name)
Create a task with explicit stack allocation.
void __os_register_task (void(*function)(void), const char *name)
Privileged implementation of os_register_task.
void __os_exit_task (void)
Privileged implementation of os_exit_task.
void __os_kill_process (uint8_t task_index)
Privileged implementation of os_kill_process.
void __os_task_suicide (void)
Privileged implementation of os_task_suicide.
Detailed Description
ICARUS Task Management Implementation.
Version
0.1.0
Task creation, registration, and lifecycle management.
Author
Souham Biswas
Date
2025
Copyright
Copyright 2025 Souham Biswas https://github.com/ironhide23586/icarus-os-core Licensed under the Apache License, Version 2.0
Definition in file task.c.
Function Documentation
__os_exit_task()
void __os_exit_task (void)
Privileged implementation of os_exit_task.
Note
Internal function - use os_exit_task() wrapper
Definition at line 82 of file task.c.
References __os_yield(), cleanup_task_idx, current_cleanup_task_idx, current_task_index, ICARUS_MAX_TASKS, running_task_count, task_list, icarus_task_t::task_state, and TASK_STATE_FINISHED.
Referenced by os_exit_task(), and SVC_Handler_C().
__os_kill_process()
void __os_kill_process (uint8_t task_index)
Privileged implementation of os_kill_process.
Note
Internal function - use os_kill_process() wrapper
Definition at line 102 of file task.c.
References __os_yield(), cleanup_task_idx, current_cleanup_task_idx, current_task_index, ICARUS_MAX_TASKS, num_created_tasks, running_task_count, task_list, icarus_task_t::task_state, and TASK_STATE_KILLED.
Referenced by __os_task_suicide(), os_kill_process(), and SVC_Handler_C().
__os_register_task()
void __os_register_task (void(* function)(void), const char * name)
Privileged implementation of os_register_task.
Note
Internal function - use os_register_task() wrapper
Definition at line 66 of file task.c.
References __kernel_get_data(), __kernel_get_stack(), ICARUS_STACK_WORDS, num_created_tasks, os_create_task(), and task_list.
Referenced by __os_init(), os_register_task(), and SVC_Handler_C().
__os_task_suicide()
void __os_task_suicide (void)
Privileged implementation of os_task_suicide.
Note
Internal function - use os_task_suicide() wrapper
Definition at line 128 of file task.c.
References __os_kill_process(), current_task_index, and task_list.
Referenced by os_task_suicide(), and SVC_Handler_C().
os_create_task()
void os_create_task (icarus_task_t * task, void(* function)(void), uint32_t * stack, uint32_t stack_size, uint32_t * data, const char * name)
Create a task with explicit stack allocation.
Parameters
task TCB to initialize
function Task entry point
stack Stack memory (8-byte aligned)
stack_size Stack size in 32-bit words
name Task name
Definition at line 27 of file task.c.
References icarus_task_t::data_pointer, icarus_task_t::function, icarus_task_t::global_tick_paused, ICARUS_MAX_TASK_NAME_LEN, ICARUS_MAX_TASKS, icarus_task_t::name, num_created_tasks, os_exit_task(), running_task_count, icarus_task_t::stack_base, icarus_task_t::stack_pointer, icarus_task_t::stack_size, icarus_task_t::task_priority, TASK_PRIORITY_LOW, icarus_task_t::task_state, TASK_STATE_COLD, and icarus_task_t::ticks_to_pause.
Referenced by __os_register_task().